// The words of the crew screens: the crew page, the crew link a friend opens,
// founding a crew, and the crew card on the profile and the wall. German pages
// are fully German and English ones fully English, one form per term
// (Crew-Link, Zockrunde, Gaming-PC; crew link, session, gaming PC), from the
// approved launch pages; a friend seat's page (st.*) too, in the approved seat
// invite's words. `{name}`, `{crew}`, `{pc}`, `{link}`, `{app}`, `{day}`,
// `{time}`, `{friend}`, `{of}` and `{n}` are filled in where they appear.

export type Lang = "en" | "de";

export const CREW_COPY = {
  en: {
    brand: "Lanterel",
    "crew.of": "{name}'s crew",
    "crew.mine": "Your crew",
    "crew.anon": "The crew",
    "pc.of": "{name}'s PC",
    "pc.anon": "A gaming PC",

    "found.title": "Start your crew",
    "found.line": "One tap and your crew is set, with a link for your group chat.",
    "found.why":
      "You'll play on a gaming PC from your crew. Nobody has one yet? No problem, one can join anytime.",
    "found.start": "Start a crew",
    "found.starting": "Starting your crew…",
    "found.signIn": "Sign in with Steam first. No password, no new account.",
    "found.failed": "Your crew couldn't be started. Try again.",
    "crews.title": "Your crews",
    "crews.new": "Start a new crew",
    "crews.people": "{n} people",
    "crews.person": "1 person",
    "crews.open": "Open",
    "crews.loading": "Loading your crews…",
    "crews.failed": "Your crews couldn't be loaded.",
    "crews.retry": "Try again",
    "crews.full":
      "You're in 50 crews already, the most anyone can be in. Leave one to start or join another.",
    "crews.line": "Play your Steam games with your people on a gaming PC from your crew. Macs included.",
    "strip.line": "Play with your people: start a crew and share the link.",
    "strip.start": "Start a crew",
    "strip.mine": "Go to your crew",
    "strip.later": "Not now",

    "cp.tag": "Crew",
    "cp.rename": "Rename",
    "cp.namePlaceholder": "Your crew's name",
    "cp.save": "Save",
    "cp.cancel": "Cancel",
    "cp.almost": "Almost ready.",
    "cp.ready": "Ready to play!",
    "cp.offline": "No PC on right now.",
    "cp.people": "People",
    "cp.peopleIn": "{n} in",
    "cp.pc": "Gaming PC",
    "cp.pcMissing": "still missing",
    "cp.pcIn": "{pc} is in",
    "cp.pcsIn": "{n} PCs in",
    "cp.pcOff": "off right now",
    "cp.next": "Next step",
    "cp.nextFound": "Get your people into the crew",
    "cp.nextFoundLine":
      "One message for your WhatsApp group or to send friends one by one. It invites them and asks who has a gaming PC.",
    "cp.whatsapp": "Share on WhatsApp",
    "cp.nextJoined": "Got a gaming PC?",
    "cp.nextJoinedLine": "Then your crew can get going. No PC? No worries, you can still play.",
    "cp.addPc": "Add a gaming PC",
    "cp.nextReady": "You're ready to play!",
    "cp.nextReadyLine": "{pc} is in. Pick a game and start playing.",
    "cp.nextReadyMany": "{n} gaming PCs are in. Pick a game and start playing.",
    "cp.play": "Play now",
    "cp.nextOffline": "No gaming PC is on right now",
    "cp.nextOfflineLine": "As soon as {pc} is back on, you can play.",
    "cp.nextOfflineMany": "As soon as one of your gaming PCs is back on, you can play.",
    "cp.nextSetup": "Almost there: set up your gaming PC",
    "cp.nextSetupLine": "Once the Lanterel app runs on your PC and its check passes, it plays for {crew}.",
    "cp.planSession": "Plan a session",
    "cp.havePc": "I've got a gaming PC",
    "cp.copy": "Copy link",
    "cp.pcLater": "Check my PC later",
    "cp.notify": "Ping me in this tab when a PC is in",
    "cp.notifyOn": "We'll ping you here while this tab is open",
    "cp.actions": "More actions",
    "cp.slots": "Your crew",
    "cp.you": "You",
    "cp.anon": "A crewmate",
    "cp.founder": "started the crew",
    "cp.joined": "just joined",
    "cp.brings": "brings the gaming PC",
    "cp.settingUp": "setting up the gaming PC",
    "cp.readyChip": "Ready",
    "cp.remove": "Remove",
    "cp.removeLabel": "Remove {name}",
    "cp.addPcLine": "Got one? Or ask the group who does.",
    "cp.missing": "missing",
    "cp.addAnotherPc": "Add another gaming PC",
    "cp.addAnotherPcLine": "Got one too? Then more of you can play at once.",
    "cp.addAnotherChip": "optional",
    "cp.pcFree": "free",
    "cp.pcBusy": "busy",
    "cp.pcAway": "offline",
    "cp.yourPc": "your PC",
    "cp.invite": "Invite people",
    "cp.inviteLine": "No limit on crew size.",
    "cp.inviteChip": "invite",
    "cp.slotsNote":
      "No limit on crew size. One person plays per gaming PC at a time, and every extra PC is one more seat.",
    "cp.progress": "How far your crew is",
    "cp.stepMade": "Crew started",
    "cp.stepPeople": "People in",
    "cp.stepPc": "Gaming PC in",
    "cp.stepReady": "Ready to play",

    "pcc.title": "Got a gaming PC? Then your crew can get going.",
    "pcc.sees": "The crew sees",
    "pcc.seesLine": "Steam, each on their own account, with their own games",
    "pcc.not": "The crew doesn't see",
    "pcc.notLine": "your Windows, your files, your home network, your Steam account",
    "pcc.note": "Only while you're not using it, and only for crews you pick. Strangers never get on.",
    "pcc.check": "Check my PC (takes a minute)",
    "pcc.later": "Later",
    "pcc.download": "Download Lanterel for Windows",
    "pcc.soon": "The Lanterel app for your PC is coming soon. Once it runs, your PC plays for {crew}.",
    "pcc.inTitle": "Your PC plays for {crew}.",
    "pcc.inLine":
      "Only while you're not using it. In the Lanterel app on your PC you pick which crews it plays for.",
    "pcc.out": "Take it out of this crew",

    "night.title": "When are you playing?",
    "night.day": "Day",
    "night.time": "Time",
    "night.today": "Today",
    "night.tomorrow": "Tomorrow",
    "night.going": "Going",
    "night.byThen": "by then?",
    "night.post": "Post the session on WhatsApp",

    "share.title": "Other ways to share",
    "share.label": "Your crew link",
    "share.or": "Or share via",
    "share.more": "More",
    "share.preview": "What your message looks like",
    "share.cardTitle": "Join the crew",
    "share.renew": "Make a new link",
    "share.renewHint": "The current link stops working.",

    "leave.open": "Leave crew",
    "leave.title": "Leave {crew}?",
    "leave.line": "Everyone else keeps playing, and the link gets you back anytime.",
    "leave.linePc":
      "Your gaming PC leaves the crew with you. Everyone else keeps playing, and the link gets you back anytime.",
    "leave.yes": "Leave",
    "leave.no": "Stay",

    "toast.copied": "Link copied",
    "toast.pasted": "Message copied. Paste it into {app}.",
    "toast.copyFailed": "Couldn't copy. Select the link and copy it yourself.",
    "toast.sent": "Link shared.",
    "toast.asked": "Question shared. When a gaming PC joins, we'll tell everyone.",
    "toast.night": "Session posted.",
    "toast.later": "Got it. You'll find it up top under “Check my PC later”.",
    "toast.failed": "That didn't work. Try again.",
    "toast.renamed": "Name saved.",
    "toast.renewed": "New link made. The old one doesn't work any more.",

    "msg.invite":
      "I set up a crew for us: {crew} 🎮 Come join. Macs work too, and everyone plays their own Steam games. Quick question: who's got a gaming PC? One's enough for all of us. {link}",
    "msg.inviteMember":
      "Come join our crew: {crew} 🎮 Macs work too, and everyone plays their own Steam games. Who's got a gaming PC? One's enough for all of us. {link}",
    "msg.inviteReady":
      "Come join our crew: {crew} 🎮 Macs work too, and everyone plays their own Steam games. {link}",
    "msg.night": "{day}, {time}: session for {crew} 🎮 Who's in? {link}",

    "ready.title": "{pc} is in. You're ready to play!",
    "ready.crew": "{crew} has a gaming PC. You're ready to play!",
    "ready.go": "Go to the crew",
    "ready.close": "Close",

    "gone.title": "This crew isn't open to you.",
    "gone.line": "Maybe you're not in it any more. The crew link gets you back in.",
    "gone.back": "To your crews",
    "crew.loading": "Loading your crew…",
    "crew.failed": "Your crew couldn't be loaded.",

    "jn.tag": "Crew invite",
    "jn.wants": "{name} wants you in",
    "jn.invited": "You're invited to",
    "jn.crewWord": "the crew",
    "jn.almost": "Almost ready. A gaming PC is still missing.",
    "jn.ready": "Ready to play. A gaming PC is in.",
    "jn.readyMany": "Ready to play. {n} gaming PCs are in.",
    "jn.offline": "A gaming PC is in, but it's off right now.",
    "jn.founder": "started the crew",
    "jn.others": "{n} already in",
    "jn.yourSeat": "Your seat",
    "jn.saving": "{name}'s saving it for you.",
    "jn.savingAnon": "It's waiting for you.",
    "jn.forYou": "for you",
    "jn.pc": "Gaming PC",
    "jn.pcLine": "Anyone can bring it, later is fine.",
    "jn.pcIn": "in",
    "jn.pcOpen": "open",
    "jn.everyone": "Everyone else",
    "jn.everyoneLine": "No limit on crew size.",
    "jn.everyoneChip": "open",
    "jn.slots": "Seats in the crew",
    "jn.step1": "Join",
    "jn.step1Line": "with Steam, no password",
    "jn.step2": "Someone brings the gaming PC",
    "jn.step2Line": "anyone, later is fine",
    "jn.step3": "Play, Macs included",
    "jn.step3Line": "everyone with their own Steam games",
    "jn.joinSteam": "Join with Steam",
    "jn.join": "Join",
    "jn.joining": "Joining…",
    "jn.note": "Free during the beta. Lanterel never sees your Steam password.",
    "jn.waiting": "{name}'s already waiting.",
    "jn.waitingAnon": "Your crew's already waiting.",
    "jn.member": "You're already in this crew.",
    "jn.toCrew": "Go to the crew",
    "jn.joinFailed": "Joining didn't work. Try again.",
    "jn.invalid": "This crew link doesn't work any more.",
    "jn.invalidLine": "Ask your group for the new link.",
    "jn.back": "Back to the start",
    "jn.loading": "Opening the invite…",
    "jn.unanswered": "The invite couldn't be opened.",
    "jn.retry": "Try again",

    "st.tag": "A seat at a friend's PC",
    "st.h1": "{name} saved you a seat",
    "st.h1b": "at their gaming PC.",
    "st.someone": "Someone",
    "st.lead":
      "{name} shares their gaming PC with friends, and one of the seats is yours. You play your own Steam games on it, from your Mac, right in Chrome.",
    "st.take": "Grab your seat",
    "st.taking": "Grabbing your seat…",
    "st.steam": "You sign in with Steam. No password, no new account.",
    "st.stub": "Saved for {friend} · {n} days",
    "st.stubOne": "Saved for {friend} · 1 day",
    "st.stubYours": "Your seat, {friend}",
    "st.stubTaken": "This seat is taken",
    "st.stubExpired": "This seat has expired",
    "st.pcAnon": "The gaming PC",
    "st.pcAnonIn": "the gaming PC",
    "st.noteOs":
      "Lanterel OS runs on {pc}, a separate system. Your Steam login doesn't stick around: it's gone once you're done.",
    "st.noteOwn": "You play with your own Steam account and your own games. Nobody shares an account.",
    "st.seatKey": "Seat",
    "st.seatValue": "{n} of {of}, for {friend}",
    "st.gpuKey": "Graphics",
    "st.nowKey": "Right now",
    "st.nowReady": "free",
    "st.nowBusy": "in use",
    "st.nowOffline": "off",
    "st.untilKey": "Valid until",
    "st.priceKey": "Price",
    "st.price": "free during the beta",
    "st.how": "How to play on {pc}",
    "st.step1": "Grab your seat",
    "st.step1Line": "With Steam, no password. That puts you in the crew that plays on this PC.",
    "st.step2": "Pick a game",
    "st.step2Line": "In Chrome on your Mac. You'll see your own Steam library and when {pc} is free.",
    "st.step3": "Start a game",
    "st.step3Line": "Scan the QR code once with the Steam app, and the game starts on {pc}.",
    "st.yours": "This seat is yours.",
    "st.toCrew": "Go to the crew",
    "st.host": "This is a seat at your own PC. Send the link to {friend}.",
    "st.taken": "Someone else already has this seat.",
    "st.takenLine": "Ask {name} for another one.",
    "st.expired": "This seat waited 14 days and has expired.",
    "st.expiredLine": "Ask {name} for a new link.",
    "st.askAnon": "Ask your friend for a new link.",
    "st.invalid": "This seat link doesn't work any more.",
    "st.loading": "Opening your seat…",
    "st.unanswered": "The seat couldn't be opened.",
    "st.failed": "Grabbing the seat didn't work. Try again.",
  },
  de: {
    brand: "Lanterel",
    "crew.of": "{name}s Crew",
    "crew.mine": "Deine Crew",
    "crew.anon": "Die Crew",
    "pc.of": "{name}s PC",
    "pc.anon": "Ein Gaming-PC",

    "found.title": "Gründe deine Crew",
    "found.line": "Ein Tipp, und deine Crew steht, mit Link für eure Gruppe.",
    "found.why":
      "Gezockt wird auf einem Gaming-PC aus eurer Crew. Hat noch keiner einen? Kein Problem, der kann jederzeit dazukommen.",
    "found.start": "Crew gründen",
    "found.starting": "Crew wird gegründet…",
    "found.signIn": "Erst mit Steam anmelden. Kein Passwort, kein neues Konto.",
    "found.failed": "Die Crew konnte nicht gegründet werden. Versuch es nochmal.",
    "crews.title": "Deine Crews",
    "crews.new": "Neue Crew gründen",
    "crews.people": "{n} Leute",
    "crews.person": "1 Person",
    "crews.open": "Öffnen",
    "crews.loading": "Deine Crews werden geladen…",
    "crews.failed": "Deine Crews konnten nicht geladen werden.",
    "crews.retry": "Nochmal versuchen",
    "crews.full":
      "Du bist schon in 50 Crews, mehr geht nicht. Verlass eine, dann kannst du eine neue gründen oder beitreten.",
    "crews.line":
      "Zock deine Steam-Spiele mit deinen Leuten, auf einem Gaming-PC aus eurer Crew. Auch auf dem Mac.",
    "strip.line": "Zock mit deinen Leuten: gründe eine Crew und teil den Link.",
    "strip.start": "Crew gründen",
    "strip.mine": "Zu deiner Crew",
    "strip.later": "Später",

    "cp.tag": "Crew",
    "cp.rename": "Name ändern",
    "cp.namePlaceholder": "Name eurer Crew",
    "cp.save": "Speichern",
    "cp.cancel": "Abbrechen",
    "cp.almost": "Fast startklar.",
    "cp.ready": "Spielbereit!",
    "cp.offline": "Gerade ist kein PC an.",
    "cp.people": "Leute",
    "cp.peopleIn": "{n} dabei",
    "cp.pc": "Gaming-PC",
    "cp.pcMissing": "fehlt noch",
    "cp.pcIn": "{pc} ist dabei",
    "cp.pcsIn": "{n} PCs dabei",
    "cp.pcOff": "gerade aus",
    "cp.next": "Nächster Schritt",
    "cp.nextFound": "Hol deine Leute in die Crew",
    "cp.nextFoundLine":
      "Eine Nachricht für eure WhatsApp-Gruppe oder an einzelne Leute. Sie lädt in die Crew ein und fragt gleich, wer einen Gaming-PC hat.",
    "cp.whatsapp": "Per WhatsApp teilen",
    "cp.nextJoined": "Hast du einen Gaming-PC?",
    "cp.nextJoinedLine":
      "Dann kann eure Crew loslegen. Hast du keinen? Kein Problem, dann zockst du einfach mit.",
    "cp.addPc": "Gaming-PC hinzufügen",
    "cp.nextReady": "Ihr seid spielbereit!",
    "cp.nextReadyLine": "{pc} ist dabei. Such dir ein Spiel aus und leg los.",
    "cp.nextReadyMany": "{n} Gaming-PCs sind dabei. Such dir ein Spiel aus und leg los.",
    "cp.play": "Jetzt zocken",
    "cp.nextOffline": "Gerade ist kein Gaming-PC an",
    "cp.nextOfflineLine": "Sobald {pc} wieder an ist, könnt ihr loslegen.",
    "cp.nextOfflineMany": "Sobald einer eurer Gaming-PCs wieder an ist, könnt ihr loslegen.",
    "cp.nextSetup": "Fast geschafft: richte deinen Gaming-PC ein",
    "cp.nextSetupLine":
      "Sobald die Lanterel-App auf deinem PC läuft und der Check bestanden ist, spielt er für {crew}.",
    "cp.planSession": "Zockrunde ansagen",
    "cp.havePc": "Ich hab einen Gaming-PC",
    "cp.copy": "Link kopieren",
    "cp.pcLater": "PC später prüfen",
    "cp.notify": "Sag mir in diesem Tab Bescheid, wenn ein PC da ist",
    "cp.notifyOn": "Wir sagen dir hier Bescheid, solange der Tab offen ist",
    "cp.actions": "Weitere Aktionen",
    "cp.slots": "Deine Crew",
    "cp.you": "Du",
    "cp.anon": "Jemand aus der Crew",
    "cp.founder": "hat die Crew gegründet",
    "cp.joined": "neu dabei",
    "cp.brings": "bringt den Gaming-PC mit",
    "cp.settingUp": "richtet den Gaming-PC ein",
    "cp.readyChip": "Bereit",
    "cp.remove": "Entfernen",
    "cp.removeLabel": "{name} entfernen",
    "cp.addPcLine": "Hast du einen? Sonst frag in der Gruppe, wer einen hat.",
    "cp.missing": "fehlt noch",
    "cp.addAnotherPc": "Noch einen Gaming-PC hinzufügen",
    "cp.addAnotherPcLine": "Hast du auch einen? Dann können mehr von euch gleichzeitig zocken.",
    "cp.addAnotherChip": "optional",
    "cp.pcFree": "frei",
    "cp.pcBusy": "belegt",
    "cp.pcAway": "offline",
    "cp.yourPc": "dein PC",
    "cp.invite": "Leute einladen",
    "cp.inviteLine": "Die Crew hat kein Limit.",
    "cp.inviteChip": "einladen",
    "cp.slotsNote":
      "Die Crew hat kein Limit. An einem Gaming-PC zockt immer einer, und jeder weitere PC ist ein Platz mehr.",
    "cp.progress": "So weit ist deine Crew",
    "cp.stepMade": "Crew gegründet",
    "cp.stepPeople": "Leute dabei",
    "cp.stepPc": "Gaming-PC dabei",
    "cp.stepReady": "Spielbereit",

    "pcc.title": "Du hast einen Gaming-PC? Dann kann eure Crew loslegen.",
    "pcc.sees": "Die Crew sieht",
    "pcc.seesLine": "Steam, jeder mit eigenem Konto und eigenen Spielen",
    "pcc.not": "Die Crew sieht nicht",
    "pcc.notLine": "dein Windows, deine Dateien, dein Heimnetz, dein Steam-Konto",
    "pcc.note":
      "Nur wenn du nicht selbst dran sitzt, und nur für Crews, die du auswählst. Fremde kommen nie an deinen PC.",
    "pcc.check": "PC prüfen, dauert eine Minute",
    "pcc.later": "Später",
    "pcc.download": "Lanterel für Windows laden",
    "pcc.soon": "Die Lanterel-App für deinen PC kommt bald. Sobald sie läuft, spielt dein PC für {crew}.",
    "pcc.inTitle": "Dein PC spielt für {crew}.",
    "pcc.inLine":
      "Nur wenn du nicht selbst dran sitzt. In der Lanterel-App auf deinem PC wählst du, für welche Crews er spielt.",
    "pcc.out": "Aus dieser Crew nehmen",

    "night.title": "Wann zockt ihr?",
    "night.day": "Tag",
    "night.time": "Uhrzeit",
    "night.today": "Heute",
    "night.tomorrow": "Morgen",
    "night.going": "Zusagen",
    "night.byThen": "bis dahin?",
    "night.post": "Zockrunde per WhatsApp ansagen",

    "share.title": "Woanders teilen",
    "share.label": "Dein Crew-Link",
    "share.or": "Oder per",
    "share.more": "Mehr",
    "share.preview": "So sieht deine Nachricht aus",
    "share.cardTitle": "Komm in die Crew",
    "share.renew": "Neuen Link erstellen",
    "share.renewHint": "Der bisherige Link funktioniert dann nicht mehr.",

    "leave.open": "Crew verlassen",
    "leave.title": "{crew} verlassen?",
    "leave.line": "Die anderen zocken weiter, und über den Link kommst du jederzeit zurück.",
    "leave.linePc":
      "Dein Gaming-PC verlässt die Crew mit dir. Die anderen zocken weiter, und über den Link kommst du jederzeit zurück.",
    "leave.yes": "Verlassen",
    "leave.no": "Doch bleiben",

    "toast.copied": "Link kopiert",
    "toast.pasted": "Nachricht kopiert. Füg sie in {app} ein.",
    "toast.copyFailed": "Kopieren ging nicht. Markier den Link und kopier ihn selbst.",
    "toast.sent": "Link geteilt.",
    "toast.asked": "Frage geteilt. Kommt ein Gaming-PC dazu, sagen wir allen Bescheid.",
    "toast.night": "Zockrunde angesagt.",
    "toast.later": "Alles klar. Du findest das oben unter „PC später prüfen“.",
    "toast.failed": "Das hat nicht geklappt. Versuch es nochmal.",
    "toast.renamed": "Name gespeichert.",
    "toast.renewed": "Neuer Link erstellt. Der alte funktioniert nicht mehr.",

    "msg.invite":
      "Ich hab eine Crew für unsere Zockrunden gegründet: {crew} 🎮 Zocken geht auch auf dem Mac, jeder mit seinen eigenen Steam-Spielen. Kurze Frage noch: Wer hat einen Gaming-PC? Einer reicht für alle. Hier geht's rein: {link}",
    "msg.inviteMember":
      "Komm in unsere Crew für die Zockrunden: {crew} 🎮 Zocken geht auch auf dem Mac, jeder mit seinen eigenen Steam-Spielen. Wer hat einen Gaming-PC? Einer reicht für alle. Hier geht's rein: {link}",
    "msg.inviteReady":
      "Komm in unsere Crew für die Zockrunden: {crew} 🎮 Zocken geht auch auf dem Mac, jeder mit seinen eigenen Steam-Spielen. Hier geht's rein: {link}",
    "msg.night": "{day}, {time}: Zockrunde 🎮 Wer ist dabei? {crew}: {link}",

    "ready.title": "{pc} ist da. Ihr seid spielbereit!",
    "ready.crew": "{crew} hat einen Gaming-PC. Ihr seid spielbereit!",
    "ready.go": "Zur Crew",
    "ready.close": "Schließen",

    "gone.title": "Diese Crew ist nicht offen für dich.",
    "gone.line": "Vielleicht bist du nicht mehr drin. Über den Crew-Link kommst du wieder rein.",
    "gone.back": "Zu deinen Crews",
    "crew.loading": "Deine Crew wird geladen…",
    "crew.failed": "Deine Crew konnte nicht geladen werden.",

    "jn.tag": "Einladung in die Crew",
    "jn.wants": "{name} holt dich in die",
    "jn.invited": "Du bist eingeladen in die",
    "jn.crewWord": "Crew",
    "jn.almost": "Fast startklar. Ein Gaming-PC fehlt noch.",
    "jn.ready": "Spielbereit. Ein Gaming-PC ist dabei.",
    "jn.readyMany": "Spielbereit. {n} Gaming-PCs sind dabei.",
    "jn.offline": "Ein Gaming-PC ist dabei, gerade ist er aus.",
    "jn.founder": "hat die Crew gegründet",
    "jn.others": "{n} sind schon drin",
    "jn.yourSeat": "Dein Platz",
    "jn.saving": "{name} hält ihn für dich frei.",
    "jn.savingAnon": "Er wartet auf dich.",
    "jn.forYou": "für dich",
    "jn.pc": "Gaming-PC",
    "jn.pcLine": "Egal, wer ihn mitbringt, auch später.",
    "jn.pcIn": "dabei",
    "jn.pcOpen": "frei",
    "jn.everyone": "Alle anderen",
    "jn.everyoneLine": "Die Crew hat kein Limit.",
    "jn.everyoneChip": "offen",
    "jn.slots": "Plätze in der Crew",
    "jn.step1": "Beitreten",
    "jn.step1Line": "mit Steam, ohne Passwort",
    "jn.step2": "Einer bringt den Gaming-PC",
    "jn.step2Line": "egal wer, auch später",
    "jn.step3": "Zocken, auch auf dem Mac",
    "jn.step3Line": "jeder mit seinen eigenen Steam-Spielen",
    "jn.joinSteam": "Mit Steam beitreten",
    "jn.join": "Beitreten",
    "jn.joining": "Beitreten…",
    "jn.note": "In der Beta kostenlos. Dein Steam-Passwort sieht Lanterel nie.",
    "jn.waiting": "{name} wartet schon.",
    "jn.waitingAnon": "Deine Crew wartet schon.",
    "jn.member": "Du bist schon in dieser Crew.",
    "jn.toCrew": "Zur Crew",
    "jn.joinFailed": "Beitreten hat nicht geklappt. Versuch es nochmal.",
    "jn.invalid": "Dieser Crew-Link funktioniert nicht mehr.",
    "jn.invalidLine": "Frag in eurer Gruppe nach dem neuen Link.",
    "jn.back": "Zur Startseite",
    "jn.loading": "Einladung wird geöffnet…",
    "jn.unanswered": "Die Einladung konnte nicht geöffnet werden.",
    "jn.retry": "Nochmal versuchen",

    "st.tag": "Ein Platz am PC eines Freundes",
    "st.h1": "{name} hält dir einen Platz",
    "st.h1b": "am Gaming-PC frei.",
    "st.someone": "Jemand",
    "st.lead":
      "{name} teilt den Gaming-PC mit Freunden, und einer der Plätze gehört dir. Deine eigenen Steam-Spiele laufen darauf, du zockst auf deinem Mac, direkt in Chrome.",
    "st.take": "Platz annehmen",
    "st.taking": "Platz wird angenommen…",
    "st.steam": "Du meldest dich mit Steam an. Kein Passwort, kein neues Konto.",
    "st.stub": "Freigehalten für {friend} · {n} Tage",
    "st.stubOne": "Freigehalten für {friend} · 1 Tag",
    "st.stubYours": "Dein Platz, {friend}",
    "st.stubTaken": "Der Platz ist vergeben",
    "st.stubExpired": "Der Platz ist abgelaufen",
    "st.pcAnon": "Der Gaming-PC",
    "st.pcAnonIn": "dem Gaming-PC",
    "st.noteOs":
      "Auf {pc} läuft Lanterel OS, ein eigenes System. Dein Steam-Login bleibt dort nicht hängen: Nach dem Zocken ist er weg.",
    "st.noteOwn":
      "Du zockst mit deinem eigenen Steam-Konto und deinen eigenen Spielen. Niemand teilt ein Konto.",
    "st.seatKey": "Platz",
    "st.seatValue": "{n} von {of}, für {friend}",
    "st.gpuKey": "Grafik",
    "st.nowKey": "Gerade",
    "st.nowReady": "frei",
    "st.nowBusy": "belegt",
    "st.nowOffline": "aus",
    "st.untilKey": "Gültig bis",
    "st.priceKey": "Preis",
    "st.price": "in der Beta kostenlos",
    "st.how": "So zockst du an {pc}",
    "st.step1": "Platz annehmen",
    "st.step1Line": "Mit Steam, ohne Passwort. Damit bist du in der Crew, die an diesem PC zockt.",
    "st.step2": "Spiel aussuchen",
    "st.step2Line":
      "In Chrome auf deinem Mac. Du siehst deine eigene Steam-Bibliothek und wann du an {pc} zocken kannst.",
    "st.step3": "Spiel starten",
    "st.step3Line": "Einmal den QR-Code mit der Steam-App scannen, dann läuft das Spiel auf {pc}.",
    "st.yours": "Der Platz gehört dir.",
    "st.toCrew": "Zur Crew",
    "st.host": "Das ist ein Platz an deinem eigenen PC. Schick den Link an {friend}.",
    "st.taken": "Diesen Platz hat schon jemand anderes.",
    "st.takenLine": "Frag {name} nach einem anderen.",
    "st.expired": "Der Platz war 14 Tage frei und ist jetzt abgelaufen.",
    "st.expiredLine": "Frag {name} nach einem neuen Link.",
    "st.askAnon": "Frag nach einem neuen Link.",
    "st.invalid": "Dieser Link zum Platz funktioniert nicht mehr.",
    "st.loading": "Dein Platz wird geöffnet…",
    "st.unanswered": "Der Platz konnte nicht geöffnet werden.",
    "st.failed": "Das hat nicht geklappt. Versuch es nochmal.",
  },
} as const satisfies Record<Lang, Record<string, string>>;

export type CopyKey = keyof (typeof CREW_COPY)["en"];

/** German for a browser set to German, English for everyone else. */
export function langOf(languages: readonly string[] = navigator.languages ?? [navigator.language]): Lang {
  return languages.some((l) => /^de\b/i.test(l)) ? "de" : "en";
}

/** The words for `lang`, with each `{slot}` filled from `fill`. */
export function crewText(lang: Lang) {
  return (key: CopyKey, fill: Record<string, string | number> = {}) =>
    (CREW_COPY[lang][key] as string).replace(/\{(\w+)\}/g, (slot, name: string) =>
      Object.hasOwn(fill, name) ? String(fill[name]) : slot,
    );
}

/**
 * Someone's name with the possessive ending, as "{name}s Crew" puts it: in
 * German a name ending in s, ß, x or z takes an apostrophe instead ("Max'
 * Crew"), in English every name takes 's.
 */
export function possessive(lang: Lang, key: "crew.of" | "pc.of", name: string): string {
  if (lang === "de" && /[sßxz]$/i.test(name)) {
    return (CREW_COPY.de[key] as string).replace("{name}s", `${name}'`);
  }
  return crewText(lang)(key, { name });
}
