// The words of the crew screens: the crew page, the crew link a friend opens,
// founding a crew, and the crew card on the profile and the wall. German pages
// are fully German and English ones fully English, one form per term
// (Crew-Link, Zockrunde, Gaming-PC; crew link, session, gaming PC), from the
// approved launch pages; a friend seat's page (st.*) too, in the approved seat
// invite's words. `{name}`, `{names}`, `{crew}`, `{pc}`, `{link}`, `{app}`, `{day}`,
// `{days}`, `{time}`, `{friend}`, `{of}`, `{when}`, `{step}`, `{game}`, `{owner}` and `{n}` are filled in where they appear.

export type Lang = "en" | "de";

export const CREW_COPY = {
  en: {
    brand: "Lanterel",
    "crew.of": "{name}'s crew",
    "crew.mine": "Your crew",
    "crew.anon": "The crew",
    "pc.of": "{name}'s PC",
    "pc.anon": "A gaming PC",

    "found.title": "Start your crew",
    "found.line": "One tap and your crew is set, with a link for your group chat.",
    "found.why":
      "You'll play on a gaming PC from your crew. Nobody has one yet? No problem, one can join anytime.",
    "found.start": "Start a crew",
    "found.signIn": "Sign in with Steam first. No password, no new account.",
    "found.failed": "Your crew couldn't be started. Try again.",
    "crews.title": "Your crews",
    "crews.new": "Start a new crew",
    "crews.people": "{n} people",
    "crews.person": "1 person",
    "crews.open": "Open",
    "crews.loading": "Loading your crews…",
    "crews.failed": "Your crews couldn't be loaded.",
    "crews.retry": "Try again",
    "crews.full":
      "You're in 50 crews already, the most anyone can be in. Leave one to start or join another.",
    "crews.line": "Play your Steam games with your people on a gaming PC from your crew. Macs included.",
    "strip.line": "Play with your people: start a crew and share the link.",
    "strip.start": "Start a crew",
    "strip.mine": "Go to your crew",
    "strip.later": "Not now",

    "cp.tag": "Crew",
    "cp.rename": "Rename",
    "cp.namePlaceholder": "Your crew's name",
    "cp.save": "Save",
    "cp.cancel": "Cancel",
    "cp.almost": "Almost ready.",
    "cp.ready": "Ready to play!",
    "cp.offline": "No PC on right now.",
    "cp.people": "People",
    "cp.peopleIn": "{n} in",
    "cp.pc": "Gaming PC",
    "cp.pcMissing": "still missing",
    "cp.pcIn": "{pc} is in",
    "cp.pcsIn": "{n} PCs in",
    "cp.pcOff": "off right now",
    "cp.next": "Next step",
    "cp.nextFound": "Get your people into the crew",
    "cp.nextFoundLine":
      "One message for your WhatsApp group or to send friends one by one. It invites them and asks who has a gaming PC.",
    "cp.whatsapp": "Share on WhatsApp",
    "cp.addPc": "Add a gaming PC",
    "cp.nextReady": "You're ready to play!",
    "cp.nextReadyLine": "{pc} is in. Pick a game and start playing.",
    "cp.nextReadyMany": "{n} gaming PCs are in. Pick a game and start playing.",
    "cp.play": "Play now",
    "cp.nextOffline": "No gaming PC is on right now",
    "cp.nextOfflineLine": "As soon as {pc} is back on, you can play.",
    "cp.nextOfflineMany": "As soon as one of your gaming PCs is back on, you can play.",
    "cp.nextSetup": "Almost there: set up your gaming PC",
    "cp.nextSetupLine": "Once the Lanterel app runs on your PC and its check passes, it plays for {crew}.",
    "cp.planSession": "Plan a session",
    "cp.havePc": "I've got a gaming PC",
    "cp.copy": "Copy link",
    "cp.notify": "Ping me in this tab when a PC is in",
    "cp.notifyOn": "We'll ping you here while this tab is open",
    "cp.actions": "More actions",
    "cp.slots": "Your crew",
    "cp.you": "You",
    "cp.anon": "A crewmate",
    "cp.readyChip": "Ready",
    "cp.remove": "Remove",
    "cp.removeLabel": "Remove {name}",
    "cp.addPcLine": "Got one? Or ask the group who does.",
    "cp.missing": "missing",
    "cp.pcFree": "free",
    "cp.pcBusy": "busy",
    "cp.pcAway": "offline",
    "cp.yourPc": "your PC",
    "cp.invite": "Invite people",
    "cp.inviteLine": "No limit on crew size.",
    "cp.inviteChip": "invite",
    "cp.slotsNote":
      "No limit on crew size. One person plays per gaming PC at a time, and every extra PC is one more seat.",
    "cp.progress": "How far your crew is",
    "cp.stepMade": "Crew started",
    "cp.stepPeople": "People in",
    "cp.stepPc": "Gaming PC in",
    "cp.stepReady": "Ready to play",

    "pcc.title": "Got a gaming PC? Then your crew can get going.",
    "pcc.sees": "The crew sees",
    "pcc.seesLine": "Steam, each on their own account, with their own games",
    "pcc.not": "The crew doesn't see",
    "pcc.notLine": "your Windows, your files, your home network, your Steam account",
    "pcc.note": "Only while you're not using it, and only for crews you pick. Strangers never get on.",
    "pcc.load": "Get the app on your PC",
    "pcc.soonShort": "The Lanterel app for your PC is coming soon.",
    "pcc.download": "Download Lanterel for Windows",
    "pcc.soon": "The Lanterel app for your PC is coming soon. Once it runs, your PC plays for {crew}.",
    "pcc.inTitle": "Your PC plays for {crew}.",
    "pcc.inLine":
      "Only while you're not using it. In the Lanterel app on your PC you pick which crews it plays for.",
    "pcc.out": "Take it out of this crew",

    "night.title": "When are you playing?",
    "night.day": "Day",
    "night.time": "Time",
    "night.today": "Today",
    "night.tomorrow": "Tomorrow",
    "night.going": "Going",
    "night.byThen": "by then?",
    "night.post": "Post the session on WhatsApp",

    "share.title": "Other ways to share",
    "share.label": "Your crew link",
    "share.or": "Or share via",
    "share.more": "More",
    "share.preview": "What your message looks like",
    "share.cardTitle": "Join the crew",
    "share.renew": "Make a new link",
    "share.renewHint": "The current link stops working.",

    "leave.open": "Leave crew",
    "leave.title": "Leave {crew}?",
    "leave.line": "Everyone else keeps playing, and the link gets you back anytime.",
    "leave.linePc":
      "Your gaming PC leaves the crew with you. Everyone else keeps playing, and the link gets you back anytime.",
    "leave.yes": "Leave",
    "leave.no": "Stay",

    "toast.copied": "Link copied",
    "toast.pasted": "Message copied. Paste it into {app}.",
    "toast.copyFailed": "Couldn't copy. Select the link and copy it yourself.",
    "toast.sent": "Link shared.",
    "toast.nudged": "Reminder shared.",
    "toast.asked": "Question shared. When a gaming PC joins, we'll tell everyone.",
    "toast.night": "Session posted.",
    "toast.failed": "That didn't work. Try again.",
    "toast.renamed": "Name saved.",
    "toast.renewed": "New link made. The old one doesn't work any more.",

    "msg.invite":
      "I set up a crew for us: {crew} 🎮 Come join. Macs work too, and everyone plays their own Steam games. Quick question: who's got a gaming PC? One's enough for all of us. {link}",
    "msg.inviteMember":
      "Come join our crew: {crew} 🎮 Macs work too, and everyone plays their own Steam games. Who's got a gaming PC? One's enough for all of us. {link}",
    "msg.inviteReady":
      "Come join our crew: {crew} 🎮 Macs work too, and everyone plays their own Steam games. {link}",
    "msg.night": "{day}, {time}: session for {crew} 🎮 Who's in? {link}",
    "g.session": "Session",
    "g.noDate": "no date yet",
    "g.onlyYou": "Only you so far",
    "g.in": "{n} in",
    "g.cant": "{n} can't",
    "g.open": "{n} haven't answered",
    "g.founded": "You founded it",
    "g.people": "{n} people",
    "g.invitedBy": "{name} invited you",
    "g.invited": "You're in the crew",
    "g.steps": "What happens before the session",
    "g.stepDate": "Date",
    "g.stepPeople": "Get your people",
    "g.stepAnswer": "Say yes or no",
    "g.stepPc": "Gaming PC",
    "g.stepPlay": "Play",
    "g.inCrew": "{n} in the crew",
    "g.change": "change",
    "g.changeLabel": "Change: {step}",
    "g.nextH": "When are you playing next?",
    "g.moveH": "Move the date",
    "g.moveP": "Pick a new day and time. Everyone is asked again.",
    "g.set": "Set {when}",
    "g.move": "Move to {when}",
    "g.peopleH": "Now get your people in",
    "g.peopleP":
      "Send the date to your WhatsApp group. Everyone taps yes or no, and you see the answers here.",
    "g.whatsapp": "Send on WhatsApp",
    "g.copy": "Copy the crew link",
    "g.preview": "Your friends get this:",
    "g.pcH": "Who brings the gaming PC?",
    "g.pcP": "One gaming PC is enough for the whole crew. Nobody has brought one yet. Do you have one?",
    "g.pcYes": "Yes: put the app on my PC",
    "g.pcNo": "No: ask the group",
    "g.pcFine": "If no gaming PC is in by the date, just move it.",
    "g.pcWaitH": "A gaming PC is still missing",
    "g.pcWaitP": "One gaming PC is enough for the whole crew. As soon as one is in, you'll see it here.",
    "g.pcAsk": "Ask the group",
    "g.pcHaveOne": "I've got one after all",
    "g.answerH": "Are you in on {when}?",
    "g.answerP": "{name} set the date. Tell the crew whether you're coming.",
    "g.answerPAnon": "The date is set. Tell the crew whether you're coming.",
    "g.yes": "I'm in",
    "g.no": "I can't",
    "g.answerFine": "Another day suits you better? Say so in your WhatsApp group.",
    "g.you": "{name} (you)",
    "g.ansYes": "In",
    "g.ansNo": "Can't",
    "g.who": "Who's coming",
    "g.ansOpen": "No answer yet",

    "ci.when": "Session on {day}, at {time}. Are you in?",
    "ci.noDate": "No date yet. Join, and you'll plan a session together.",
    "ci.in": "I'm in",
    "ci.withSteam": "Join with Steam",
    "ci.joinCrew": "Join the crew",
    "ci.cant": "Can't make it, but join the crew anyway",
    "ci.fine": "No password, no new account. Free during the beta.",
    "ci.yourSeat": "Your spot",
    "ci.pcMissing": "Gaming PC: still missing.",
    "ci.pcMissingLine": "Got one? After joining, you can add it with one tap.",
    "ci.pcIn": "Gaming PC: in.",
    "ci.pcInMany": "{n} gaming PCs: in.",
    "ci.pcInLine": "Everyone plays on it, Macs included.",
    "ci.pcOff": "Gaming PC: in, but off right now.",
    "ci.pcOffLine": "Whoever has it turns it on for the session.",
    "ci.how": "How it works",
    "ci.how1": "Tap “I'm in”",
    "ci.how1Join": "Tap “Join the crew”",
    "ci.how1Line": "Steam confirms who you are. No password, no new account.",
    "ci.how2": "On {day}, open the crew page",
    "ci.how2Any": "For the session, open the crew page",
    "ci.how2Line": "On your Mac, in Chrome. Nothing to install.",
    "ci.how3": "Take turns playing",
    "ci.how3Line": "One plays on the gaming PC, the others watch and chat on voice.",

    "pl.onNow": "On now",
    "pl.freeH": "The gaming PC is free. Who goes first?",
    "pl.freeP":
      "Pick one of your games and start it. It runs on {pc} and opens on your screen in full screen. Whoever starts first plays first, the others watch.",
    "pl.yours": "Your games that run on {pc}",
    "pl.loading": "Loading your games…",
    "pl.none": "None of your Steam games runs on {pc} yet.",
    "pl.start": "Start {game}",
    "pl.fine": "You scan a QR code once with the Steam app. {owner} doesn't have to do anything.",
    "pl.fineMine": "You scan a QR code once with the Steam app.",
    "pl.ownFree": "Your PC is free; your crew can start on it.",
    "pl.failed": "That didn't work: someone else just started. Watch, or get in line.",
    "pl.playingH": "{name} is playing {game}",
    "pl.startingH": "{name} is starting {game}",
    "pl.youH": "You're playing {game}",
    "pl.claimedH": "Someone is just starting a game on {pc}",
    "pl.claimedP": "In a moment you can watch or get in line.",
    "pl.someone": "Someone",
    "pl.aGame": "a game",
    "pl.for": "for {n} min",
    "pl.on": "on {pc}",
    "pl.watching": "{n} watching",
    "pl.watch": "Watch",
    "pl.next": "I want to go next",
    "pl.leave": "Leave the line",
    "pl.queue": "Who's next",
    "pl.queueYou": "You",
    "pl.pick": "What do you want to play?",
    "pl.queueFine": "When {name} stops, whoever is first in line goes next.",
    "pl.queueFineAnon": "When this round ends, whoever is first in line goes next.",
    "pl.pcLine": "{pc} is on. It plays for this crew only.",
    "g.more": "More about the crew",
    "g.on": "{day} at {time}",
    "msg.date": "Session on {when} 🎮",
    "msg.dateFrom": "{name} is inviting you to the crew. Tap to say yes or no:",
    "msg.dateAnon": "You're invited to the crew. Tap to say yes or no:",
    "msg.datePc": "Who's got a gaming PC? One is enough for all of us.",
    "cal.h": "Pick a day in the calendar",
    "cal.p": "Any day works.",
    "cal.pBusy": "Days marked in orange: the gaming PC is already booked for another session.",
    "cal.prev": "Previous month",
    "cal.next": "Next month",
    "cal.today": "today",
    "cal.busyKey": "gaming PC already booked",
    "cal.timeOn": "Time on {day}",
    "cal.warn": "{days}: {pc} already plays for another crew from {time}.",
    "cal.warnMine": "{days}: Your PC already plays for another crew from {time}.",
    "cal.warnAsk": "On those days, pick an earlier time or ask {name}.",
    "cal.warnAskOne": "On that day, pick an earlier time or ask {name}.",
    "cal.warnEarlier": "On those days, pick an earlier time.",
    "cal.warnEarlierOne": "On that day, pick an earlier time.",
    "cal.fine": "Everyone in the crew gets the date and says yes or no.",
    "cal.summary": "Session: {crew}",
    "cal.description": "Your crew page: {link}",
    "who.h": "Who's coming on {day}",
    "who.yes": "In",
    "who.no": "Can't",
    "who.open": "No answer yet",
    "who.nudge": "Nudge {name}",
    "who.nudgeOne": "Nudge them",
    "who.nudgeN": "Nudge {n} people",
    "who.calendar": "Add to my calendar",
    "who.move": "Move the date (everyone answers again)",
    "who.sees": "This is what {name} sees in the invite:",
    "who.seesAnon": "This is what your friends see in the invite:",
    "who.miniH": "Session on {when}. Are you in?",
    "who.miniIn": "{names} are in.",
    "who.miniInOne": "{names} is in.",
    "who.remind": "Add it to your calendar and it reminds you an hour before.",
    "msg.nudge": "{name}, are you in on {when}? Tap to say yes or no:",
    "msg.nudgeAnon": "Are you in on {when}? Tap to say yes or no:",
    "g.stepGames": "Pick games",
    "g.picked": "{n} games",
    "g.pickedOne": "1 game",
    "gm.h": "What do you want to play on {day}?",
    "gm.hAny": "What do you want to play?",
    "gm.p":
      "Tap every game you feel like. The crew sees what most people want. You only see games that run on the crew's gaming PC.",
    "gm.fav": "Crew favourite",
    "gm.favN": "{n} of {of} want it",
    "gm.all": "Everyone can play these",
    "gm.allSub": "you all own them, or they're free",
    "gm.some": "Only some of you have these",
    "gm.someSub": "only the owners can play them, the rest can watch",
    "gm.free": "Free, anyone can play",
    "gm.ownAll": "You all have it",
    "gm.own": "{n} of {of} have it",
    "gm.wantN": "{n} want it",
    "gm.want1": "1 wants it",
    "gm.want0": "nobody yet",
    "gm.done": "Done: {n} games marked",
    "gm.doneOne": "Done: 1 game marked",
    "gm.doneNone": "Done",
    "gm.fine": "You can change it any time, even on {day}.",
    "gm.fineAny": "You can change it any time.",
    "gm.loading": "Loading the games…",
    "gm.failed": "The games couldn't be loaded.",
    "gm.empty":
      "No games on the crew's gaming PC yet. As soon as it reports its Steam games, they show up here.",

    "ready.title": "{pc} is in. You're ready to play!",
    "ready.crew": "{crew} has a gaming PC. You're ready to play!",
    "ready.go": "Go to the crew",
    "ready.close": "Close",

    "gone.title": "This crew isn't open to you.",
    "gone.line": "Maybe you're not in it any more. The crew link gets you back in.",
    "gone.back": "To your crews",
    "crew.loading": "Loading your crew…",
    "crew.failed": "Your crew couldn't be loaded.",

    "jn.tag": "Crew invite",
    "jn.wants": "{name} wants you in",
    "jn.invited": "You're invited to",
    "jn.crewWord": "the crew",
    "jn.when": "Session on {when}.",
    "jn.going": "In so far: {n}. Join and say yes or no.",
    "jn.almost": "Almost ready. A gaming PC is still missing.",
    "jn.ready": "Ready to play. A gaming PC is in.",
    "jn.readyMany": "Ready to play. {n} gaming PCs are in.",
    "jn.offline": "A gaming PC is in, but it's off right now.",
    "jn.founder": "started the crew",
    "jn.others": "{n} already in",
    "jn.yourSeat": "Your seat",
    "jn.saving": "{name}'s saving it for you.",
    "jn.savingAnon": "It's waiting for you.",
    "jn.forYou": "for you",
    "jn.pc": "Gaming PC",
    "jn.pcLine": "Anyone can bring it, later is fine.",
    "jn.pcIn": "in",
    "jn.pcOpen": "open",
    "jn.everyone": "Everyone else",
    "jn.everyoneLine": "No limit on crew size.",
    "jn.everyoneChip": "open",
    "jn.slots": "Seats in the crew",
    "jn.step1": "Join",
    "jn.step1Line": "with Steam, no password",
    "jn.step2": "Someone brings the gaming PC",
    "jn.step2Line": "anyone, later is fine",
    "jn.step3": "Play, Macs included",
    "jn.step3Line": "everyone with their own Steam games",
    "jn.joinSteam": "Join with Steam",
    "jn.join": "Join",
    "jn.joining": "Joining…",
    "jn.note": "Free during the beta. Lanterel never sees your Steam password.",
    "jn.waiting": "{name}'s already waiting.",
    "jn.waitingAnon": "Your crew's already waiting.",
    "jn.member": "You're already in this crew.",
    "jn.toCrew": "Go to the crew",
    "jn.joinFailed": "Joining didn't work. Try again.",
    "jn.invalid": "This crew link doesn't work any more.",
    "jn.invalidLine": "Ask your group for the new link.",
    "jn.back": "Back to the start",
    "jn.loading": "Opening the invite…",
    "jn.unanswered": "The invite couldn't be opened.",
    "jn.retry": "Try again",

    "st.tag": "A seat at a friend's PC",
    "st.h1": "{name} saved you a seat",
    "st.h1b": "at their gaming PC.",
    "st.someone": "Someone",
    "st.lead":
      "{name} shares their gaming PC with friends, and one of the seats is yours. You play your own Steam games on it, from your Mac, right in Chrome.",
    "st.take": "Grab your seat",
    "st.taking": "Grabbing your seat…",
    "st.steam": "You sign in with Steam. No password, no new account.",
    "st.stub": "Saved for {friend} · {n} days",
    "st.stubOne": "Saved for {friend} · 1 day",
    "st.stubYours": "Your seat, {friend}",
    "st.stubTaken": "This seat is taken",
    "st.stubExpired": "This seat has expired",
    "st.pcAnon": "The gaming PC",
    "st.pcAnonIn": "the gaming PC",
    "st.noteOs":
      "Lanterel OS runs on {pc}, a separate system. Your Steam login doesn't stick around: it's gone once you're done.",
    "st.noteOwn": "You play with your own Steam account and your own games. Nobody shares an account.",
    "st.seatKey": "Seat",
    "st.seatValue": "{n} of {of}, for {friend}",
    "st.gpuKey": "Graphics",
    "st.nowKey": "Right now",
    "st.nowReady": "free",
    "st.nowBusy": "in use",
    "st.nowOffline": "off",
    "st.untilKey": "Valid until",
    "st.priceKey": "Price",
    "st.price": "free during the beta",
    "st.how": "How to play on {pc}",
    "st.step1": "Grab your seat",
    "st.step1Line": "With Steam, no password. That puts you in the crew that plays on this PC.",
    "st.step2": "Pick a game",
    "st.step2Line": "In Chrome on your Mac. You'll see your own Steam library and when {pc} is free.",
    "st.step3": "Start a game",
    "st.step3Line": "Scan the QR code once with the Steam app, and the game starts on {pc}.",
    "st.yours": "This seat is yours.",
    "st.toCrew": "Go to the crew",
    "st.host": "This is a seat at your own PC. Send the link to {friend}.",
    "st.taken": "Someone else already has this seat.",
    "st.takenLine": "Ask {name} for another one.",
    "st.expired": "This seat waited 14 days and has expired.",
    "st.expiredLine": "Ask {name} for a new link.",
    "st.askAnon": "Ask your friend for a new link.",
    "st.invalid": "This seat link doesn't work any more.",
    "st.loading": "Opening your seat…",
    "st.unanswered": "The seat couldn't be opened.",
    "st.failed": "Grabbing the seat didn't work. Try again.",
  },
  de: {
    brand: "Lanterel",
    "crew.of": "{name}s Crew",
    "crew.mine": "Deine Crew",
    "crew.anon": "Die Crew",
    "pc.of": "{name}s PC",
    "pc.anon": "Ein Gaming-PC",

    "found.title": "Gründe deine Crew",
    "found.line": "Ein Tipp, und deine Crew steht, mit Link für eure Gruppe.",
    "found.why":
      "Gezockt wird auf einem Gaming-PC aus eurer Crew. Hat noch keiner einen? Kein Problem, der kann jederzeit dazukommen.",
    "found.start": "Crew gründen",
    "found.signIn": "Erst mit Steam anmelden. Kein Passwort, kein neues Konto.",
    "found.failed": "Die Crew konnte nicht gegründet werden. Versuch es nochmal.",
    "crews.title": "Deine Crews",
    "crews.new": "Neue Crew gründen",
    "crews.people": "{n} Leute",
    "crews.person": "1 Person",
    "crews.open": "Öffnen",
    "crews.loading": "Deine Crews werden geladen…",
    "crews.failed": "Deine Crews konnten nicht geladen werden.",
    "crews.retry": "Nochmal versuchen",
    "crews.full":
      "Du bist schon in 50 Crews, mehr geht nicht. Verlass eine, dann kannst du eine neue gründen oder beitreten.",
    "crews.line":
      "Zock deine Steam-Spiele mit deinen Leuten, auf einem Gaming-PC aus eurer Crew. Auch auf dem Mac.",
    "strip.line": "Zock mit deinen Leuten: gründe eine Crew und teil den Link.",
    "strip.start": "Crew gründen",
    "strip.mine": "Zu deiner Crew",
    "strip.later": "Später",

    "cp.tag": "Crew",
    "cp.rename": "Name ändern",
    "cp.namePlaceholder": "Name eurer Crew",
    "cp.save": "Speichern",
    "cp.cancel": "Abbrechen",
    "cp.almost": "Fast startklar.",
    "cp.ready": "Spielbereit!",
    "cp.offline": "Gerade ist kein PC an.",
    "cp.people": "Leute",
    "cp.peopleIn": "{n} dabei",
    "cp.pc": "Gaming-PC",
    "cp.pcMissing": "fehlt noch",
    "cp.pcIn": "{pc} ist dabei",
    "cp.pcsIn": "{n} PCs dabei",
    "cp.pcOff": "gerade aus",
    "cp.next": "Nächster Schritt",
    "cp.nextFound": "Hol deine Leute in die Crew",
    "cp.nextFoundLine":
      "Eine Nachricht für eure WhatsApp-Gruppe oder an einzelne Leute. Sie lädt in die Crew ein und fragt gleich, wer einen Gaming-PC hat.",
    "cp.whatsapp": "Per WhatsApp teilen",
    "cp.addPc": "Gaming-PC hinzufügen",
    "cp.nextReady": "Ihr seid spielbereit!",
    "cp.nextReadyLine": "{pc} ist dabei. Such dir ein Spiel aus und leg los.",
    "cp.nextReadyMany": "{n} Gaming-PCs sind dabei. Such dir ein Spiel aus und leg los.",
    "cp.play": "Jetzt zocken",
    "cp.nextOffline": "Gerade ist kein Gaming-PC an",
    "cp.nextOfflineLine": "Sobald {pc} wieder an ist, könnt ihr loslegen.",
    "cp.nextOfflineMany": "Sobald einer eurer Gaming-PCs wieder an ist, könnt ihr loslegen.",
    "cp.nextSetup": "Fast geschafft: richte deinen Gaming-PC ein",
    "cp.nextSetupLine":
      "Sobald die Lanterel-App auf deinem PC läuft und der Check bestanden ist, spielt er für {crew}.",
    "cp.planSession": "Zockrunde ansagen",
    "cp.havePc": "Ich hab einen Gaming-PC",
    "cp.copy": "Link kopieren",
    "cp.notify": "Sag mir in diesem Tab Bescheid, wenn ein PC da ist",
    "cp.notifyOn": "Wir sagen dir hier Bescheid, solange der Tab offen ist",
    "cp.actions": "Weitere Aktionen",
    "cp.slots": "Deine Crew",
    "cp.you": "Du",
    "cp.anon": "Jemand aus der Crew",
    "cp.readyChip": "Bereit",
    "cp.remove": "Entfernen",
    "cp.removeLabel": "{name} entfernen",
    "cp.addPcLine": "Hast du einen? Sonst frag in der Gruppe, wer einen hat.",
    "cp.missing": "fehlt noch",
    "cp.pcFree": "frei",
    "cp.pcBusy": "belegt",
    "cp.pcAway": "offline",
    "cp.yourPc": "dein PC",
    "cp.invite": "Leute einladen",
    "cp.inviteLine": "Die Crew hat kein Limit.",
    "cp.inviteChip": "einladen",
    "cp.slotsNote":
      "Die Crew hat kein Limit. An einem Gaming-PC zockt immer einer, und jeder weitere PC ist ein Platz mehr.",
    "cp.progress": "So weit ist deine Crew",
    "cp.stepMade": "Crew gegründet",
    "cp.stepPeople": "Leute dabei",
    "cp.stepPc": "Gaming-PC dabei",
    "cp.stepReady": "Spielbereit",

    "pcc.title": "Du hast einen Gaming-PC? Dann kann eure Crew loslegen.",
    "pcc.sees": "Die Crew sieht",
    "pcc.seesLine": "Steam, jeder mit eigenem Konto und eigenen Spielen",
    "pcc.not": "Die Crew sieht nicht",
    "pcc.notLine": "dein Windows, deine Dateien, dein Heimnetz, dein Steam-Konto",
    "pcc.note":
      "Nur wenn du nicht selbst dran sitzt, und nur für Crews, die du auswählst. Fremde kommen nie an deinen PC.",
    "pcc.load": "App auf den PC laden",
    "pcc.soonShort": "Die Lanterel-App für deinen PC kommt in Kürze.",
    "pcc.download": "Lanterel für Windows laden",
    "pcc.soon": "Die Lanterel-App für deinen PC kommt in Kürze. Sobald sie läuft, spielt dein PC für {crew}.",
    "pcc.inTitle": "Dein PC spielt für {crew}.",
    "pcc.inLine":
      "Nur wenn du nicht selbst dran sitzt. In der Lanterel-App auf deinem PC wählst du, für welche Crews er spielt.",
    "pcc.out": "Aus dieser Crew nehmen",

    "night.title": "Wann zockt ihr?",
    "night.day": "Tag",
    "night.time": "Uhrzeit",
    "night.today": "Heute",
    "night.tomorrow": "Morgen",
    "night.going": "Zusagen",
    "night.byThen": "bis dahin?",
    "night.post": "Zockrunde per WhatsApp ansagen",

    "share.title": "Woanders teilen",
    "share.label": "Dein Crew-Link",
    "share.or": "Oder per",
    "share.more": "Mehr",
    "share.preview": "So sieht deine Nachricht aus",
    "share.cardTitle": "Komm in die Crew",
    "share.renew": "Neuen Link erstellen",
    "share.renewHint": "Der bisherige Link funktioniert dann nicht mehr.",

    "leave.open": "Crew verlassen",
    "leave.title": "{crew} verlassen?",
    "leave.line": "Die anderen zocken weiter, und über den Link kommst du jederzeit zurück.",
    "leave.linePc":
      "Dein Gaming-PC verlässt die Crew mit dir. Die anderen zocken weiter, und über den Link kommst du jederzeit zurück.",
    "leave.yes": "Verlassen",
    "leave.no": "Doch bleiben",

    "toast.copied": "Link kopiert",
    "toast.pasted": "Nachricht kopiert. Füg sie in {app} ein.",
    "toast.copyFailed": "Kopieren ging nicht. Markier den Link und kopier ihn selbst.",
    "toast.sent": "Link geteilt.",
    "toast.nudged": "Erinnerung geteilt.",
    "toast.asked": "Frage geteilt. Kommt ein Gaming-PC dazu, sagen wir allen Bescheid.",
    "toast.night": "Zockrunde angesagt.",
    "toast.failed": "Das hat nicht geklappt. Versuch es nochmal.",
    "toast.renamed": "Name gespeichert.",
    "toast.renewed": "Neuer Link erstellt. Der alte funktioniert nicht mehr.",

    "msg.invite":
      "Ich hab eine Crew für unsere Zockrunden gegründet: {crew} 🎮 Zocken geht auch auf dem Mac, jeder mit seinen eigenen Steam-Spielen. Kurze Frage noch: Wer hat einen Gaming-PC? Einer reicht für alle. Hier geht's rein: {link}",
    "msg.inviteMember":
      "Komm in unsere Crew für die Zockrunden: {crew} 🎮 Zocken geht auch auf dem Mac, jeder mit seinen eigenen Steam-Spielen. Wer hat einen Gaming-PC? Einer reicht für alle. Hier geht's rein: {link}",
    "msg.inviteReady":
      "Komm in unsere Crew für die Zockrunden: {crew} 🎮 Zocken geht auch auf dem Mac, jeder mit seinen eigenen Steam-Spielen. Hier geht's rein: {link}",
    "msg.night": "{day}, {time}: Zockrunde 🎮 Wer ist dabei? {crew}: {link}",
    "g.session": "Zockrunde",
    "g.noDate": "noch kein Termin",
    "g.onlyYou": "Bis jetzt nur du",
    "g.in": "{n} dabei",
    "g.cant": "{n} kann nicht",
    "g.open": "{n} offen",
    "g.founded": "Du hast sie gegründet",
    "g.people": "{n} Leute",
    "g.invitedBy": "{name} hat dich eingeladen",
    "g.invited": "Du bist in der Crew",
    "g.steps": "Was bis zur Zockrunde passiert",
    "g.stepDate": "Termin",
    "g.stepPeople": "Leute holen",
    "g.stepAnswer": "Zusagen",
    "g.stepPc": "Gaming-PC",
    "g.stepPlay": "Zocken",
    "g.inCrew": "{n} in der Crew",
    "g.change": "ändern",
    "g.changeLabel": "{step} ändern",
    "g.nextH": "Wann zockt ihr als Nächstes?",
    "g.moveH": "Termin verschieben",
    "g.moveP": "Such dir einen neuen Tag und eine Uhrzeit aus. Alle werden nochmal gefragt.",
    "g.set": "{when} festlegen",
    "g.move": "Auf {when} verschieben",
    "g.peopleH": "Jetzt hol deine Leute",
    "g.peopleP":
      "Schick den Termin in eure WhatsApp-Gruppe. Jeder sagt mit einem Tipp zu oder ab, und du siehst die Antworten hier.",
    "g.whatsapp": "Per WhatsApp schicken",
    "g.copy": "Crew-Link kopieren",
    "g.preview": "So kommt es bei deinen Leuten an:",
    "g.pcH": "Wer bringt den Gaming-PC?",
    "g.pcP":
      "Ein Gaming-PC reicht für die ganze Crew. Bis jetzt hat noch keiner einen mitgebracht. Hast du einen?",
    "g.pcYes": "Ja: App auf meinen PC laden",
    "g.pcNo": "Nein: in der Gruppe fragen",
    "g.pcFine": "Ist bis zum Termin noch kein Gaming-PC dabei, verschieb ihn einfach.",
    "g.pcWaitH": "Noch fehlt ein Gaming-PC",
    "g.pcWaitP": "Ein Gaming-PC reicht für die ganze Crew. Sobald einer dabei ist, siehst du es hier.",
    "g.pcAsk": "In der Gruppe fragen",
    "g.pcHaveOne": "Ich hab doch einen",
    "g.answerH": "Bist du am {when} dabei?",
    "g.answerP": "{name} hat den Termin festgelegt. Sag der Crew, ob du kommst.",
    "g.answerPAnon": "Der Termin steht. Sag der Crew, ob du kommst.",
    "g.yes": "Bin dabei",
    "g.no": "Kann nicht",
    "g.answerFine": "Passt dir ein anderer Tag besser? Sag es in eurer WhatsApp-Gruppe.",
    "g.you": "{name} (du)",
    "g.ansYes": "Dabei",
    "g.ansNo": "Kann nicht",
    "g.who": "Wer kommt",
    "g.ansOpen": "Noch offen",

    "ci.when": "Zockrunde am {day}, um {time}. Bist du dabei?",
    "ci.noDate": "Noch kein Termin. Tritt bei, dann sagt ihr zusammen eine Zockrunde an.",
    "ci.in": "Bin dabei",
    "ci.withSteam": "Mit Steam beitreten",
    "ci.joinCrew": "Crew beitreten",
    "ci.cant": "Kann nicht, aber trotzdem in die Crew",
    "ci.fine": "Kein Passwort, kein neues Konto. In der Beta kostenlos.",
    "ci.yourSeat": "Dein Platz",
    "ci.pcMissing": "Gaming-PC: fehlt noch.",
    "ci.pcMissingLine": "Hast du einen? Nach dem Beitreten holst du ihn mit einem Tipp dazu.",
    "ci.pcIn": "Gaming-PC: ist dabei.",
    "ci.pcInMany": "{n} Gaming-PCs: sind dabei.",
    "ci.pcInLine": "Alle zocken darauf, auch auf dem Mac.",
    "ci.pcOff": "Gaming-PC: ist dabei, gerade aus.",
    "ci.pcOffLine": "Wer ihn hat, macht ihn zur Zockrunde an.",
    "ci.how": "So läuft's",
    "ci.how1": "„Bin dabei“ tippen",
    "ci.how1Join": "„Crew beitreten“ tippen",
    "ci.how1Line": "Steam bestätigt, wer du bist. Kein Passwort, kein neues Konto.",
    "ci.how2": "Am {day} die Crew-Seite öffnen",
    "ci.how2Any": "Zur Zockrunde die Crew-Seite öffnen",
    "ci.how2Line": "Auf dem Mac, in Chrome. Nichts installieren.",
    "ci.how3": "Abwechselnd zocken",
    "ci.how3Line": "Einer zockt auf dem Gaming-PC, die anderen schauen zu und quatschen im Voice.",

    "pl.onNow": "Läuft gerade",
    "pl.freeH": "Der Gaming-PC ist frei. Wer fängt an?",
    "pl.freeP":
      "Such dir eins deiner Spiele aus und starte es. Es läuft auf {pc} und geht bei dir im Vollbild auf. Wer zuerst startet, zockt zuerst, die anderen schauen zu.",
    "pl.yours": "Deine Spiele, die auf {pc} laufen",
    "pl.loading": "Deine Spiele werden geladen…",
    "pl.none": "Auf {pc} läuft noch keins deiner Steam-Spiele.",
    "pl.start": "{game} starten",
    "pl.fine": "Du scannst einmal einen QR-Code mit der Steam-App. {owner} muss nichts machen.",
    "pl.fineMine": "Du scannst einmal einen QR-Code mit der Steam-App.",
    "pl.ownFree": "Dein PC ist frei, deine Crew kann darauf starten.",
    "pl.failed": "Das hat nicht geklappt: Gerade hat jemand anderes gestartet. Schau zu oder stell dich an.",
    "pl.playingH": "{name} zockt gerade {game}",
    "pl.startingH": "{name} startet gerade {game}",
    "pl.youH": "Du zockst gerade {game}",
    "pl.claimedH": "Gerade startet jemand ein Spiel auf {pc}",
    "pl.claimedP": "Gleich kannst du zuschauen oder dich anstellen.",
    "pl.someone": "Jemand",
    "pl.aGame": "ein Spiel",
    "pl.for": "seit {n} Min.",
    "pl.on": "auf {pc}",
    "pl.watching": "{n} schauen zu",
    "pl.watch": "Zuschauen",
    "pl.next": "Ich will als Nächstes",
    "pl.leave": "Doch nicht",
    "pl.queue": "Wer als Nächstes dran ist",
    "pl.queueYou": "Du",
    "pl.pick": "Was willst du zocken?",
    "pl.queueFine": "Hört {name} auf, ist als Nächstes dran, wer vorne steht.",
    "pl.queueFineAnon": "Ist die Runde vorbei, ist als Nächstes dran, wer vorne steht.",
    "pl.pcLine": "{pc} ist an. Er spielt nur für diese Crew.",
    "g.more": "Mehr zur Crew",
    "g.on": "{day} um {time}",
    "msg.date": "Zockrunde am {when} 🎮",
    "msg.dateFrom": "{name} lädt dich in die Crew ein. Tipp drauf und sag zu oder ab:",
    "msg.dateAnon": "Du bist in die Crew eingeladen. Tipp drauf und sag zu oder ab:",
    "msg.datePc": "Wer hat einen Gaming-PC? Einer reicht für alle.",
    "cal.h": "Such dir einen Tag im Kalender aus",
    "cal.p": "Jeder Tag geht.",
    "cal.pBusy": "Orange markierte Tage: Da ist der Gaming-PC schon für eine andere Zockrunde verplant.",
    "cal.prev": "Voriger Monat",
    "cal.next": "Nächster Monat",
    "cal.today": "heute",
    "cal.busyKey": "Gaming-PC schon verplant",
    "cal.timeOn": "Uhrzeit am {day}",
    "cal.warn": "{days}: {pc} spielt da schon ab {time} für eine andere Crew.",
    "cal.warnMine": "{days}: Dein PC spielt da schon ab {time} für eine andere Crew.",
    "cal.warnAsk": "An diesen Tagen such dir eine frühere Uhrzeit aus oder frag {name}.",
    "cal.warnAskOne": "An dem Tag such dir eine frühere Uhrzeit aus oder frag {name}.",
    "cal.warnEarlier": "An diesen Tagen such dir eine frühere Uhrzeit aus.",
    "cal.warnEarlierOne": "An dem Tag such dir eine frühere Uhrzeit aus.",
    "cal.fine": "Alle in der Crew bekommen den Termin und sagen zu oder ab.",
    "cal.summary": "Zockrunde: {crew}",
    "cal.description": "Eure Crew-Seite: {link}",
    "who.h": "Wer am {day} kommt",
    "who.yes": "Dabei",
    "who.no": "Kann nicht",
    "who.open": "Noch keine Antwort",
    "who.nudge": "{name} erinnern",
    "who.nudgeOne": "Erinnern",
    "who.nudgeN": "{n} Leute erinnern",
    "who.calendar": "In meinen Kalender",
    "who.move": "Termin verschieben (alle sagen neu zu)",
    "who.sees": "So sieht {name} die Einladung:",
    "who.seesAnon": "So sehen deine Freunde die Einladung:",
    "who.miniH": "Zockrunde am {when}. Bist du dabei?",
    "who.miniIn": "{names} sind dabei.",
    "who.miniInOne": "{names} ist dabei.",
    "who.remind": "Im Kalender erinnert er dich eine Stunde vorher.",
    "msg.nudge": "{name}, bist du am {when} dabei? Sag kurz zu oder ab:",
    "msg.nudgeAnon": "Bist du am {when} dabei? Sag kurz zu oder ab:",
    "g.stepGames": "Spiele wählen",
    "g.picked": "{n} Spiele",
    "g.pickedOne": "1 Spiel",
    "gm.h": "Was willst du am {day} zocken?",
    "gm.hAny": "Was willst du zocken?",
    "gm.p":
      "Tipp alle Spiele an, auf die du Lust hast. Die Crew sieht, was die meisten wollen. Du siehst nur Spiele, die auf dem Gaming-PC der Crew laufen.",
    "gm.fav": "Favorit der Crew",
    "gm.favN": "{n} von {of} wollen das",
    "gm.all": "Kann jeder zocken",
    "gm.allSub": "ihr habt sie alle, oder sie sind gratis",
    "gm.some": "Haben nur ein paar",
    "gm.someSub": "zocken können nur die, die es haben, die anderen schauen zu",
    "gm.free": "Gratis, jeder kann",
    "gm.ownAll": "Habt ihr alle",
    "gm.own": "{n} von {of} haben es",
    "gm.wantN": "{n} wollen",
    "gm.want1": "1 will",
    "gm.want0": "noch keiner",
    "gm.done": "Fertig: {n} Spiele markiert",
    "gm.doneOne": "Fertig: 1 Spiel markiert",
    "gm.doneNone": "Fertig",
    "gm.fine": "Du kannst das jederzeit ändern, auch noch am {day}.",
    "gm.fineAny": "Du kannst das jederzeit ändern.",
    "gm.loading": "Spiele werden geladen…",
    "gm.failed": "Die Spiele konnten nicht geladen werden.",
    "gm.empty":
      "Auf dem Gaming-PC der Crew sind noch keine Spiele. Sobald er seine Steam-Spiele meldet, stehen sie hier.",

    "ready.title": "{pc} ist da. Ihr seid spielbereit!",
    "ready.crew": "{crew} hat einen Gaming-PC. Ihr seid spielbereit!",
    "ready.go": "Zur Crew",
    "ready.close": "Schließen",

    "gone.title": "Diese Crew ist nicht offen für dich.",
    "gone.line": "Vielleicht bist du nicht mehr drin. Über den Crew-Link kommst du wieder rein.",
    "gone.back": "Zu deinen Crews",
    "crew.loading": "Deine Crew wird geladen…",
    "crew.failed": "Deine Crew konnte nicht geladen werden.",

    "jn.tag": "Einladung in die Crew",
    "jn.wants": "{name} holt dich in die",
    "jn.invited": "Du bist eingeladen in die",
    "jn.crewWord": "Crew",
    "jn.when": "Zockrunde am {when}.",
    "jn.going": "Bis jetzt dabei: {n}. Tritt bei und sag zu oder ab.",
    "jn.almost": "Fast startklar. Ein Gaming-PC fehlt noch.",
    "jn.ready": "Spielbereit. Ein Gaming-PC ist dabei.",
    "jn.readyMany": "Spielbereit. {n} Gaming-PCs sind dabei.",
    "jn.offline": "Ein Gaming-PC ist dabei, gerade ist er aus.",
    "jn.founder": "hat die Crew gegründet",
    "jn.others": "{n} sind schon drin",
    "jn.yourSeat": "Dein Platz",
    "jn.saving": "{name} hält ihn für dich frei.",
    "jn.savingAnon": "Er wartet auf dich.",
    "jn.forYou": "für dich",
    "jn.pc": "Gaming-PC",
    "jn.pcLine": "Egal, wer ihn mitbringt, auch später.",
    "jn.pcIn": "dabei",
    "jn.pcOpen": "frei",
    "jn.everyone": "Alle anderen",
    "jn.everyoneLine": "Die Crew hat kein Limit.",
    "jn.everyoneChip": "offen",
    "jn.slots": "Plätze in der Crew",
    "jn.step1": "Beitreten",
    "jn.step1Line": "mit Steam, ohne Passwort",
    "jn.step2": "Einer bringt den Gaming-PC",
    "jn.step2Line": "egal wer, auch später",
    "jn.step3": "Zocken, auch auf dem Mac",
    "jn.step3Line": "jeder mit seinen eigenen Steam-Spielen",
    "jn.joinSteam": "Mit Steam beitreten",
    "jn.join": "Beitreten",
    "jn.joining": "Beitreten…",
    "jn.note": "In der Beta kostenlos. Dein Steam-Passwort sieht Lanterel nie.",
    "jn.waiting": "{name} wartet schon.",
    "jn.waitingAnon": "Deine Crew wartet schon.",
    "jn.member": "Du bist schon in dieser Crew.",
    "jn.toCrew": "Zur Crew",
    "jn.joinFailed": "Beitreten hat nicht geklappt. Versuch es nochmal.",
    "jn.invalid": "Dieser Crew-Link funktioniert nicht mehr.",
    "jn.invalidLine": "Frag in eurer Gruppe nach dem neuen Link.",
    "jn.back": "Zur Startseite",
    "jn.loading": "Einladung wird geöffnet…",
    "jn.unanswered": "Die Einladung konnte nicht geöffnet werden.",
    "jn.retry": "Nochmal versuchen",

    "st.tag": "Ein Platz am PC eines Freundes",
    "st.h1": "{name} hält dir einen Platz",
    "st.h1b": "am Gaming-PC frei.",
    "st.someone": "Jemand",
    "st.lead":
      "{name} teilt den Gaming-PC mit Freunden, und einer der Plätze gehört dir. Deine eigenen Steam-Spiele laufen darauf, du zockst auf deinem Mac, direkt in Chrome.",
    "st.take": "Platz annehmen",
    "st.taking": "Platz wird angenommen…",
    "st.steam": "Du meldest dich mit Steam an. Kein Passwort, kein neues Konto.",
    "st.stub": "Freigehalten für {friend} · {n} Tage",
    "st.stubOne": "Freigehalten für {friend} · 1 Tag",
    "st.stubYours": "Dein Platz, {friend}",
    "st.stubTaken": "Der Platz ist vergeben",
    "st.stubExpired": "Der Platz ist abgelaufen",
    "st.pcAnon": "Der Gaming-PC",
    "st.pcAnonIn": "dem Gaming-PC",
    "st.noteOs":
      "Auf {pc} läuft Lanterel OS, ein eigenes System. Dein Steam-Login bleibt dort nicht hängen: Nach dem Zocken ist er weg.",
    "st.noteOwn":
      "Du zockst mit deinem eigenen Steam-Konto und deinen eigenen Spielen. Niemand teilt ein Konto.",
    "st.seatKey": "Platz",
    "st.seatValue": "{n} von {of}, für {friend}",
    "st.gpuKey": "Grafik",
    "st.nowKey": "Gerade",
    "st.nowReady": "frei",
    "st.nowBusy": "belegt",
    "st.nowOffline": "aus",
    "st.untilKey": "Gültig bis",
    "st.priceKey": "Preis",
    "st.price": "in der Beta kostenlos",
    "st.how": "So zockst du an {pc}",
    "st.step1": "Platz annehmen",
    "st.step1Line": "Mit Steam, ohne Passwort. Damit bist du in der Crew, die an diesem PC zockt.",
    "st.step2": "Spiel aussuchen",
    "st.step2Line":
      "In Chrome auf deinem Mac. Du siehst deine eigene Steam-Bibliothek und wann du an {pc} zocken kannst.",
    "st.step3": "Spiel starten",
    "st.step3Line": "Einmal den QR-Code mit der Steam-App scannen, dann läuft das Spiel auf {pc}.",
    "st.yours": "Der Platz gehört dir.",
    "st.toCrew": "Zur Crew",
    "st.host": "Das ist ein Platz an deinem eigenen PC. Schick den Link an {friend}.",
    "st.taken": "Diesen Platz hat schon jemand anderes.",
    "st.takenLine": "Frag {name} nach einem anderen.",
    "st.expired": "Der Platz war 14 Tage frei und ist jetzt abgelaufen.",
    "st.expiredLine": "Frag {name} nach einem neuen Link.",
    "st.askAnon": "Frag nach einem neuen Link.",
    "st.invalid": "Dieser Link zum Platz funktioniert nicht mehr.",
    "st.loading": "Dein Platz wird geöffnet…",
    "st.unanswered": "Der Platz konnte nicht geöffnet werden.",
    "st.failed": "Das hat nicht geklappt. Versuch es nochmal.",
  },
} as const satisfies Record<Lang, Record<string, string>>;

export type CopyKey = keyof (typeof CREW_COPY)["en"];

/** German for a browser set to German, English for everyone else. */
export function langOf(languages: readonly string[] = navigator.languages ?? [navigator.language]): Lang {
  return languages.some((l) => /^de\b/i.test(l)) ? "de" : "en";
}

/** `text` with each `{slot}` filled from `fill`; a slot `fill` lacks stays as it is. */
export function fillSlots(text: string, fill: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (slot, name: string) =>
    Object.hasOwn(fill, name) ? String(fill[name]) : slot,
  );
}

/** The words for `lang`, with each `{slot}` filled from `fill`. */
export function crewText(lang: Lang) {
  return (key: CopyKey, fill: Record<string, string | number> = {}) => fillSlots(CREW_COPY[lang][key], fill);
}

/**
 * Someone's name with the possessive ending, as "{name}s Crew" puts it: in
 * German a name ending in s, ß, x or z takes an apostrophe instead ("Max'
 * Crew"), in English every name takes 's.
 */
export function possessive(lang: Lang, key: "crew.of" | "pc.of", name: string): string {
  if (lang === "de" && /[sßxz]$/i.test(name)) {
    return (CREW_COPY.de[key] as string).replace("{name}s", `${name}'`);
  }
  return crewText(lang)(key, { name });
}
