// The words of the top bar and the wall, beside crewCopy.ts's crew screens and
// in the same language: German for a browser set to German (langOf), English
// for everyone else. `{name}`-style slots are filled where they appear.

import { createContext, useContext, useMemo } from "react";
import { fillSlots, langOf, type Lang } from "./crewCopy";
import type { Screen } from "./useSwiff";

export const SCREEN_COPY = {
  en: {
    "bar.back": "Back to all games",
    "bar.backTitle": "All games · Esc",
    "bar.home": "Home",
    "bar.profile": "Profile",
    "bar.share": "Share your PC",
    "bar.profileOf": "Profile, {who}",
    "bar.profileOut": "Profile, not signed in",
    "bar.signedIn": "Signed in",
    "bar.signedInLower": "signed in",
    "bar.steam": "Steam connected",
    "bar.notSignedIn": "Not signed in",
    "bar.playTime": "Play time",
    "bar.playTimeTitle": "How much play time do you have? Ready means a machine is free for all of it.",
    "session.quick": "1 h",
    "session.evening": "3 h",
    "session.night": "All night",
    "live.game": "{n} free for this game",
    "live.near": "{n} free near you",
    "live.ready1": "1 game ready now",
    "live.ready": "{n} games ready now",
    "wall.allNight": "All night",
    "wall.freeAllNight": "free all night",
    "wall.freeUntil": "free until {at}",
    "wall.backAt": "Back at {at}",
    "wall.freeShort": "Free, not long enough",
    "wall.inUse": "In use",
    "wall.noMachine": "Not on a machine yet",
    "wall.emptyBack": "Every shared machine is in use. {name} is back at {at}. ",
    "wall.emptyShort": "No free machine lasts your whole play time. Try a shorter play time, up top. ",
    "wall.emptyBusy": "Every shared machine is in use. ",
    "wall.emptyNone": "No shared machine is free right now. ",
    "wall.games": "Games",
    "wall.library": "Your library",
    "wall.f2p": "Free to play",
    "wall.readyNow": "Ready now",
    "wall.popular": "Popular on Steam",
    "wall.allGames": "All {n} games",
    "wall.denied": "Steam sign-in was cancelled. Sign in with Steam to play.",
    "wall.artCredit":
      "Game artwork and trailers are the property of their respective publishers, served from Steam.",
    "hero.leaderOut": "Now on Lanterel",
    "hero.fromLibrary": "From your library",
    "hero.played": "{n} h played",
    "hero.inLibrary": "In your library",
    "hero.on": "On",
    "hero.finding": "Finding you a machine…",
    "hero.gpu": "GPU",
    "hero.response": "Response",
    "hero.freeUntil": "Free until",
    "hero.resume": "Resume",
    "hero.play": "Play",
    "hero.left": "{left} free",
    "hero.kickOut": "Play now, no download",
    "hero.onGpu": "on a",
    "hero.onShared": "on a",
    "hero.sharedPc": "shared PC",
    "hero.noDownload": "No download.",
    "hero.pitch":
      "We read your Steam library and stream the games you own from players’ idle PCs. Your saves come with you.",
    "hero.fine": "We only read your game library.",
    "tile.signInOwn": "Sign in to play if you own it",
    "tile.finding": "Finding a machine…",
    "tile.signIn": "Sign in to play",
    "tile.free": "Free",
    "library.unreadable": "We couldn't read your Steam library.",
    "library.unreadableBody": "In Steam, set Profile → Privacy → Game details to Public, then retry.",
    "library.checking": "Checking your games…",
    "library.checkingBody": "Each one shows up here once we know Lanterel can run it.",
    "library.none": "None of your Steam games can be played here yet.",
    "library.noneBody": "Free-to-play games still work.",
    "library.retrying": "Checking…",
    "library.checkAgain": "Check again",
    "library.retry": "Retry",
    "empty.title": "Nothing is ready right now",
    "empty.signedIn": "{state}We'll tell you the moment something frees up.",
    "empty.signedOut": "{state}Sign in with Steam and we'll tell you when a PC frees up.",
    "empty.notify": "Notify me",
    "signIn.steam": "Sign in with Steam",
    "game.yours": "your game",
    "game.Yours": "Your game",
    "ig.starting": "Starting {title}",
    "ig.kicker": "Starting",
    "ig.on": "on {host}",
    "ig.nowOn": "now on {host}",
    "ig.aMachine": "a machine",
    "ig.away": ", {ms} ms away",
    "ig.end": "End",
    "ig.cancel": "Cancel",
    "ig.slowSay": "{step}: taking longer than usual",
    "ig.slow": "Taking longer than usual",
    "ig.tryAnother": "Try another machine",
    "ig.done": "Done",
    "ig.stopped": "Stopped",
    "ig.next": "Next",
    "ig.reserving": "Reserving a machine",
    "ig.waking": "Waking {host}",
    "ig.wakingAny": "Waking the machine",
    "ig.negotiating": "Negotiating stream",
    "ig.launching": "Launching {game}",
    "ig.launchingAny": "Launching your game",
    "qr.code": "Steam sign-in QR code",
    "qr.title": "Sign in to Steam",
    "qr.scan": "Scan this with the Steam app on your phone and approve. Your game starts as soon as you do.",
    "qr.note": "Steam shows where the PC is on a map. Approve only while this screen is open.",
    "qr.launchFailed": "Your game didn't start",
    "qr.timeUp": "Sign-in time ran out",
    "qr.failed": "Sign-in didn't work",
    "qr.launchFailedText": "Steam signed you in, but your game didn't come up on this machine.",
    "qr.timeUpText": "Your {n} minutes to sign in to Steam ran out, so this machine went back.",
    "qr.failedText":
      "Steam didn't finish signing you in, so your game hasn't started. Try again for a new code.",
    "qr.bookAgain": "Book again",
    "qr.retry": "Try again",
    "back.on": "on {host}",
    "back.end": "End session",
    "back.reconnect": "Reconnect",
    "away.label": "{game} is still yours",
    "away.kicker": "Still yours",
    "away.yourMachine": "your machine",
    "away.running": "Still running",
    "away.held": "Held for you",
    "away.live": "Live",
    "away.line": "It kept running when the page closed. Pick it up where you left off.",
    "away.reconnecting": "Reconnecting…",
    "away.unreachable": "We couldn't reach {host}. Press Reconnect to try again.",
    "queue.finding": "Still finding a machine",
    "queue.reading": "In the queue",
    "queue.held": "Held",
    "queue.line":
      "Your place in the queue is held while Lanterel stays open, and kept for 2 minutes if you close it. Your game starts by itself the moment a machine is free.",
    "queue.keep": "Keep waiting",
    "queue.leave": "Leave the queue",
    "rc.cantReach": "Can't reach {host}",
    "rc.label": "Reconnecting to {host}",
    "rc.lost": "Connection lost",
    "rc.kicker": "Reconnecting",
    "rc.timeAway": "Time away",
    "rc.gaveUp": "Your game is still running on {host}. Press Reconnect while it's held for you.",
    "rc.line": "Your game keeps running while we get you back.",
    "lost.taken": "{host} was taken back",
    "lost.offline": "{host} went offline",
    "lost.ownerTook": "{host}’s owner took it back",
    "lost.none": "No machine to move to",
    "lost.moving": "Moving you to another machine",
    "lost.takenKicker": "Taken back",
    "lost.kicker": "Machine lost",
    "lost.cantMove": "Couldn't move you",
    "lost.waiting": "Waiting for a machine",
    "lost.finding": "Finding another machine",
    "lost.failedLine": "No other machine could carry {title} on. Choose one yourself, or stop for now.",
    "lost.waitingLine":
      "Every machine with {title} is busy. You keep your place, and it starts by itself the moment one is free.",
    "lost.movingLine": "Your session carries on by itself on the best other machine with {title}.",
    "lost.choose": "Choose a machine",
    "lost.stop": "Stop for now",
  },
  de: {
    "bar.back": "Zurück zu allen Spielen",
    "bar.backTitle": "Alle Spiele · Esc",
    "bar.home": "Start",
    "bar.profile": "Profil",
    "bar.share": "PC freigeben",
    "bar.profileOf": "Profil, {who}",
    "bar.profileOut": "Profil, nicht angemeldet",
    "bar.signedIn": "Angemeldet",
    "bar.signedInLower": "angemeldet",
    "bar.steam": "Steam-Konto verbunden",
    "bar.notSignedIn": "Nicht angemeldet",
    "bar.playTime": "Spielzeit",
    "bar.playTimeTitle": "Wie viel Spielzeit hast du? Bereit heißt: Ein PC ist die ganze Zeit frei.",
    "session.quick": "1 Std.",
    "session.evening": "3 Std.",
    "session.night": "Die ganze Nacht",
    "live.game": "{n} frei für dieses Spiel",
    "live.near": "{n} frei in deiner Nähe",
    "live.ready1": "1 Spiel jetzt bereit",
    "live.ready": "{n} Spiele jetzt bereit",
    "wall.allNight": "Die ganze Nacht",
    "wall.freeAllNight": "die ganze Nacht frei",
    "wall.freeUntil": "frei bis {at}",
    "wall.backAt": "Zurück um {at}",
    "wall.freeShort": "Frei, aber nicht die ganze Zeit",
    "wall.inUse": "Belegt",
    "wall.noMachine": "Noch auf keinem PC",
    "wall.emptyBack": "Jeder geteilte PC ist belegt. {name} ist um {at} zurück. ",
    "wall.emptyShort": "Kein freier PC reicht für deine ganze Spielzeit. Wähl oben eine kürzere Spielzeit. ",
    "wall.emptyBusy": "Jeder geteilte PC ist belegt. ",
    "wall.emptyNone": "Gerade ist kein geteilter PC frei. ",
    "wall.games": "Spiele",
    "wall.library": "Deine Steam-Bibliothek",
    "wall.f2p": "Free-to-Play",
    "wall.readyNow": "Jetzt bereit",
    "wall.popular": "Beliebt auf Steam",
    "wall.allGames": "Alle {n} Spiele",
    "wall.denied": "Die Anmeldung bei Steam wurde abgebrochen. Melde dich mit Steam an, um zu spielen.",
    "wall.artCredit": "Spielgrafiken und Videos gehören ihren jeweiligen Herausgebern und kommen von Steam.",
    "hero.leaderOut": "Jetzt auf Lanterel",
    "hero.fromLibrary": "Aus deiner Steam-Bibliothek",
    "hero.played": "{n} Std. gespielt",
    "hero.inLibrary": "In deiner Steam-Bibliothek",
    "hero.on": "Auf",
    "hero.finding": "Wir suchen dir einen PC…",
    "hero.gpu": "Grafikkarte",
    "hero.response": "Antwortzeit",
    "hero.freeUntil": "Frei bis",
    "hero.resume": "Weiterspielen",
    "hero.play": "Spielen",
    "hero.left": "{left} frei",
    "hero.kickOut": "Sofort zocken, ohne Herunterladen",
    "hero.onGpu": "auf einer",
    "hero.onShared": "auf einem",
    "hero.sharedPc": "geteilten PC",
    "hero.noDownload": "Ohne Herunterladen.",
    "hero.pitch":
      "Wir lesen deine Steam-Bibliothek und streamen deine Spiele von freien PCs anderer Leute. Deine Spielstände kommen mit.",
    "hero.fine": "Wir lesen nur deine Spielebibliothek.",
    "tile.signInOwn": "Anmelden und spielen, falls du es hast",
    "tile.finding": "Wir suchen einen PC…",
    "tile.signIn": "Anmelden und spielen",
    "tile.free": "Gratis",
    "library.unreadable": "Wir konnten deine Steam-Bibliothek nicht lesen.",
    "library.unreadableBody":
      "Stell in Steam Profil → Privatsphäre → Spieldetails auf Öffentlich und versuch es noch einmal.",
    "library.checking": "Wir prüfen deine Spiele…",
    "library.checkingBody": "Jedes Spiel taucht hier auf, sobald klar ist, dass es auf Lanterel läuft.",
    "library.none": "Noch keins deiner Steam-Spiele läuft hier.",
    "library.noneBody": "Free-to-Play-Spiele laufen trotzdem.",
    "library.retrying": "Wird geprüft…",
    "library.checkAgain": "Noch einmal prüfen",
    "library.retry": "Noch einmal",
    "empty.title": "Gerade ist nichts bereit",
    "empty.signedIn": "{state}Wir sagen dir Bescheid, sobald etwas frei wird.",
    "empty.signedOut": "{state}Melde dich mit Steam an, dann sagen wir dir, wenn ein PC frei wird.",
    "empty.notify": "Sag mir Bescheid",
    "signIn.steam": "Mit Steam anmelden",
    "game.yours": "dein Spiel",
    "game.Yours": "Dein Spiel",
    "ig.starting": "{title} startet",
    "ig.kicker": "Startet",
    "ig.on": "auf {host}",
    "ig.nowOn": "jetzt auf {host}",
    "ig.aMachine": "einem PC",
    "ig.away": ", {ms} ms entfernt",
    "ig.end": "Beenden",
    "ig.cancel": "Abbrechen",
    "ig.slowSay": "{step}: dauert länger als sonst",
    "ig.slow": "Dauert länger als sonst",
    "ig.tryAnother": "Anderen PC versuchen",
    "ig.done": "Fertig",
    "ig.stopped": "Angehalten",
    "ig.next": "Als Nächstes",
    "ig.reserving": "PC wird reserviert",
    "ig.waking": "{host} wird geweckt",
    "ig.wakingAny": "Der PC wird geweckt",
    "ig.negotiating": "Stream wird eingerichtet",
    "ig.launching": "{game} wird gestartet",
    "ig.launchingAny": "Dein Spiel wird gestartet",
    "qr.code": "QR-Code zur Anmeldung bei Steam",
    "qr.title": "Bei Steam anmelden",
    "qr.scan":
      "Scanne den Code mit der Steam-App auf deinem Handy und bestätige. Dein Spiel startet, sobald du bestätigst.",
    "qr.note":
      "Steam zeigt auf einer Karte, wo der PC steht. Bestätige nur, solange dieser Bildschirm offen ist.",
    "qr.launchFailed": "Dein Spiel ist nicht gestartet",
    "qr.timeUp": "Die Zeit zum Anmelden ist abgelaufen",
    "qr.failed": "Die Anmeldung hat nicht geklappt",
    "qr.launchFailedText": "Steam hat dich angemeldet, aber dein Spiel ist auf diesem PC nicht gestartet.",
    "qr.timeUpText":
      "Deine {n} Minuten zum Anmelden bei Steam sind abgelaufen, deshalb ist dieser PC nicht mehr für dich reserviert.",
    "qr.failedText":
      "Steam hat die Anmeldung nicht abgeschlossen, dein Spiel ist also nicht gestartet. Versuch es noch einmal mit einem neuen Code.",
    "qr.bookAgain": "Neu buchen",
    "qr.retry": "Noch einmal",
    "back.on": "auf {host}",
    "back.end": "Sitzung beenden",
    "back.reconnect": "Neu verbinden",
    "away.label": "{game} läuft noch für dich",
    "away.kicker": "Noch deins",
    "away.yourMachine": "deinem PC",
    "away.running": "Läuft noch",
    "away.held": "Für dich reserviert",
    "away.live": "Läuft",
    "away.line": "Dein Spiel lief weiter, während die Seite zu war. Mach da weiter, wo du aufgehört hast.",
    "away.reconnecting": "Wird neu verbunden…",
    "away.unreachable": "{host} ist gerade nicht erreichbar. Drück auf Neu verbinden.",
    "queue.finding": "Wir suchen noch einen PC",
    "queue.reading": "In der Warteschlange",
    "queue.held": "Gesichert",
    "queue.line":
      "Dein Platz in der Warteschlange bleibt, solange Lanterel offen ist, und noch 2 Minuten, wenn du es schließt. Dein Spiel startet von selbst, sobald ein PC frei ist.",
    "queue.keep": "Weiter warten",
    "queue.leave": "Warteschlange verlassen",
    "rc.cantReach": "{host} ist nicht erreichbar",
    "rc.label": "Wir verbinden dich neu mit {host}",
    "rc.lost": "Verbindung verloren",
    "rc.kicker": "Verbindet neu",
    "rc.timeAway": "Ohne Verbindung",
    "rc.gaveUp":
      "Dein Spiel läuft noch auf {host}. Drück auf Neu verbinden, solange der PC für dich reserviert ist.",
    "rc.line": "Dein Spiel läuft weiter, während wir dich zurückholen.",
    "lost.taken": "{host} wurde zurückgeholt",
    "lost.offline": "{host} ist nicht mehr erreichbar",
    "lost.ownerTook": "Der Besitzer von {host} hat ihn zurückgeholt",
    "lost.none": "Kein PC zum Wechseln",
    "lost.moving": "Wir bringen dich auf einen anderen PC",
    "lost.takenKicker": "Zurückgeholt",
    "lost.kicker": "PC verloren",
    "lost.cantMove": "Wechsel nicht möglich",
    "lost.waiting": "Wir warten auf einen PC",
    "lost.finding": "Wir suchen einen anderen PC",
    "lost.failedLine":
      "Kein anderer PC konnte {title} übernehmen. Such dir selbst einen aus oder hör erst mal auf.",
    "lost.waitingLine":
      "Jeder PC mit {title} ist belegt. Du behältst deinen Platz, und es startet von selbst, sobald einer frei ist.",
    "lost.movingLine": "Deine Sitzung geht von selbst auf dem besten anderen PC mit {title} weiter.",
    "lost.choose": "PC auswählen",
    "lost.stop": "Erst mal aufhören",
  },
} as const satisfies Record<Lang, Record<string, string>>;

export type ScreenKey = keyof (typeof SCREEN_COPY)["en"];

/** The screens translated whole: the wall, an invite, a seat and the crew pages. Every other screen is English only. */
const TRANSLATED: ReadonlySet<Screen> = new Set(["home", "invite", "seat", "crew"]);

/**
 * The language `screen` speaks, and everything on it with it: the top bar, the
 * crew card and banner, the dialogs and Ignition. The browser's on a translated
 * screen, else English.
 */
export const screenLang = (screen: Screen, lang: Lang = langOf()): Lang =>
  TRANSLATED.has(screen) ? lang : "en";

/** The words for `lang`, with each `{slot}` filled from `fill`. */
export function screenText(lang: Lang) {
  return (key: ScreenKey, fill: Record<string, string | number> = {}) =>
    fillSlots(SCREEN_COPY[lang][key], fill);
}

export type ScreenText = ReturnType<typeof screenText>;

/** The language of the screen being shown (Swiff.tsx sets it from screenLang); English outside one. */
export const ScreenLang = createContext<Lang>("en");

/** The words of the screen being shown, and its language. */
export function useScreenText(): { lang: Lang; t: ScreenText } {
  const lang = useContext(ScreenLang);
  return useMemo(() => ({ lang, t: screenText(lang) }), [lang]);
}
