// The words of the top bar and the wall, beside crewCopy.ts's crew screens and
// in the same language: German for a browser set to German (langOf), English
// for everyone else. `{name}`-style slots are filled where they appear.

import { fillSlots, type Lang } from "./crewCopy";

export const SCREEN_COPY = {
  en: {
    "bar.back": "Back to all games",
    "bar.backTitle": "All games · Esc",
    "bar.home": "Home",
    "bar.profile": "Profile",
    "bar.share": "Share your PC",
    "bar.profileOf": "Profile, {who}",
    "bar.profileOut": "Profile, not signed in",
    "bar.signedIn": "Signed in",
    "bar.signedInLower": "signed in",
    "bar.steam": "Steam connected",
    "bar.notSignedIn": "Not signed in",
    "bar.playTime": "Play time",
    "bar.playTimeTitle": "How much play time do you have? Ready means a machine is free for all of it.",
    "session.quick": "1 h",
    "session.evening": "3 h",
    "session.night": "All night",
    "live.game": "{n} free for this game",
    "live.near": "{n} free near you",
    "live.ready1": "1 game ready now",
    "live.ready": "{n} games ready now",
    "wall.allNight": "All night",
    "wall.freeAllNight": "free all night",
    "wall.freeUntil": "free until {at}",
    "wall.backAt": "Back at {at}",
    "wall.freeShort": "Free, not all session",
    "wall.inUse": "In use",
    "wall.noMachine": "On no machine yet",
    "wall.emptyBack": "Every shared machine is in use. {name} is back at {at}. ",
    "wall.emptyShort": "No free machine lasts your whole play time. Try a shorter play time, up top. ",
    "wall.emptyBusy": "Every shared machine is in use. ",
    "wall.emptyNone": "No shared machine is free right now. ",
    "wall.games": "Games",
    "wall.library": "Your library",
    "wall.f2p": "Free to play",
    "wall.readyNow": "Ready now",
    "wall.popular": "Popular on Steam",
    "wall.allGames": "All {n} games",
    "wall.denied": "Steam sign-in was cancelled. Sign in with Steam to play.",
    "wall.artCredit":
      "Game artwork and trailers are the property of their respective publishers, served from Steam.",
    "hero.leaderOut": "Now on Lanterel",
    "hero.fromLibrary": "From your library",
    "hero.played": "{n} h played",
    "hero.inLibrary": "In your library",
    "hero.on": "On",
    "hero.finding": "Finding you a machine…",
    "hero.gpu": "GPU",
    "hero.response": "Response",
    "hero.freeUntil": "Free until",
    "hero.resume": "Resume",
    "hero.play": "Play",
    "hero.left": "{left} free",
    "hero.kickOut": "Play now, no download",
    "hero.onGpu": "on a",
    "hero.onShared": "on a",
    "hero.sharedPc": "shared PC",
    "hero.noDownload": "No download.",
    "hero.pitch":
      "We read your Steam library and stream the games you own from players’ idle PCs. Your saves come with you.",
    "hero.fine": "We only read your game library.",
    "tile.signInOwn": "Sign in to play if you own it",
    "tile.finding": "Finding a machine…",
    "tile.signIn": "Sign in to play",
    "tile.free": "Free",
    "library.unreadable": "We couldn't read your Steam library.",
    "library.unreadableBody": "In Steam, set Profile → Privacy → Game details to Public, then retry.",
    "library.checking": "Checking your games…",
    "library.checkingBody": "Each one shows up here once we know Lanterel can run it.",
    "library.none": "None of your Steam games can be played here yet.",
    "library.noneBody": "Free-to-play games still work.",
    "library.retrying": "Checking…",
    "library.checkAgain": "Check again",
    "library.retry": "Retry",
    "empty.title": "Nothing is ready right now",
    "empty.signedIn": "{state}We'll tell you the moment something frees up.",
    "empty.signedOut": "{state}Sign in with Steam and we'll tell you when a PC frees up.",
    "empty.notify": "Notify me",
    "signIn.steam": "Sign in with Steam",
  },
  de: {
    "bar.back": "Zurück zu allen Spielen",
    "bar.backTitle": "Alle Spiele · Esc",
    "bar.home": "Start",
    "bar.profile": "Profil",
    "bar.share": "PC freigeben",
    "bar.profileOf": "Profil, {who}",
    "bar.profileOut": "Profil, nicht angemeldet",
    "bar.signedIn": "Angemeldet",
    "bar.signedInLower": "angemeldet",
    "bar.steam": "Steam-Konto verbunden",
    "bar.notSignedIn": "Nicht angemeldet",
    "bar.playTime": "Spielzeit",
    "bar.playTimeTitle": "Wie viel Spielzeit hast du? Bereit heißt: Ein PC ist die ganze Zeit frei.",
    "session.quick": "1 Std.",
    "session.evening": "3 Std.",
    "session.night": "Die ganze Nacht",
    "live.game": "{n} frei für dieses Spiel",
    "live.near": "{n} frei in deiner Nähe",
    "live.ready1": "1 Spiel jetzt bereit",
    "live.ready": "{n} Spiele jetzt bereit",
    "wall.allNight": "Die ganze Nacht",
    "wall.freeAllNight": "die ganze Nacht frei",
    "wall.freeUntil": "frei bis {at}",
    "wall.backAt": "Zurück um {at}",
    "wall.freeShort": "Frei, aber nicht die ganze Zeit",
    "wall.inUse": "Belegt",
    "wall.noMachine": "Noch auf keinem PC",
    "wall.emptyBack": "Jeder geteilte PC ist belegt. {name} ist um {at} zurück. ",
    "wall.emptyShort": "Kein freier PC reicht für deine ganze Spielzeit. Wähl oben eine kürzere Spielzeit. ",
    "wall.emptyBusy": "Jeder geteilte PC ist belegt. ",
    "wall.emptyNone": "Gerade ist kein geteilter PC frei. ",
    "wall.games": "Spiele",
    "wall.library": "Deine Steam-Bibliothek",
    "wall.f2p": "Free-to-Play",
    "wall.readyNow": "Jetzt bereit",
    "wall.popular": "Beliebt auf Steam",
    "wall.allGames": "Alle {n} Spiele",
    "wall.denied": "Die Anmeldung bei Steam wurde abgebrochen. Melde dich mit Steam an, um zu spielen.",
    "wall.artCredit": "Spielgrafiken und Videos gehören ihren jeweiligen Herausgebern und kommen von Steam.",
    "hero.leaderOut": "Jetzt auf Lanterel",
    "hero.fromLibrary": "Aus deiner Steam-Bibliothek",
    "hero.played": "{n} Std. gespielt",
    "hero.inLibrary": "In deiner Steam-Bibliothek",
    "hero.on": "Auf",
    "hero.finding": "Wir suchen dir einen PC…",
    "hero.gpu": "Grafikkarte",
    "hero.response": "Antwortzeit",
    "hero.freeUntil": "Frei bis",
    "hero.resume": "Weiterspielen",
    "hero.play": "Spielen",
    "hero.left": "{left} frei",
    "hero.kickOut": "Sofort zocken, ohne Herunterladen",
    "hero.onGpu": "auf einer",
    "hero.onShared": "auf einem",
    "hero.sharedPc": "geteilten PC",
    "hero.noDownload": "Ohne Herunterladen.",
    "hero.pitch":
      "Wir lesen deine Steam-Bibliothek und übertragen deine Spiele von freien PCs anderer Leute. Deine Spielstände kommen mit.",
    "hero.fine": "Wir lesen nur deine Spielebibliothek.",
    "tile.signInOwn": "Anmelden und spielen, wenn es dir gehört",
    "tile.finding": "Wir suchen einen PC…",
    "tile.signIn": "Anmelden und spielen",
    "tile.free": "Gratis",
    "library.unreadable": "Wir konnten deine Steam-Bibliothek nicht lesen.",
    "library.unreadableBody":
      "Stell in Steam Profil → Privatsphäre → Spieldetails auf Öffentlich und versuch es noch einmal.",
    "library.checking": "Wir prüfen deine Spiele…",
    "library.checkingBody": "Jedes erscheint hier, sobald wir wissen, dass Lanterel es spielen kann.",
    "library.none": "Noch keins deiner Steam-Spiele läuft hier.",
    "library.noneBody": "Free-to-Play-Spiele gehen trotzdem.",
    "library.retrying": "Wird geprüft…",
    "library.checkAgain": "Noch einmal prüfen",
    "library.retry": "Noch einmal",
    "empty.title": "Gerade ist nichts bereit",
    "empty.signedIn": "{state}Wir sagen dir Bescheid, sobald etwas frei wird.",
    "empty.signedOut": "{state}Melde dich mit Steam an, dann sagen wir dir, wenn ein PC frei wird.",
    "empty.notify": "Bescheid geben",
    "signIn.steam": "Mit Steam anmelden",
  },
} as const satisfies Record<Lang, Record<string, string>>;

export type ScreenKey = keyof (typeof SCREEN_COPY)["en"];

/** The words for `lang`, with each `{slot}` filled from `fill`. */
export function screenText(lang: Lang) {
  return (key: ScreenKey, fill: Record<string, string | number> = {}) =>
    fillSlots(SCREEN_COPY[lang][key], fill);
}
