// TURN relay for peers that cannot reach each other directly: symmetric NAT,
// carrier CGNAT, firewalls that only let 443 out. Configured here rather than
// in the clients so neither the renter page nor the host .exe has to be
// rebuilt to change it, and so the renter never has to be asked for anything.
//
// Two ways to supply it, checked in this order:
//
//   1. TURN_KEY_ID + TURN_KEY_API_TOKEN
//      The provider's long-term secret. This process mints short-lived
//      credentials from it and refreshes them before they expire — the
//      arrangement Cloudflare documents, and the only one that does not break
//      every time a ttl runs out.
//
//   2. TURN_URLS [+ TURN_USERNAME + TURN_CREDENTIAL]
//      A pair generated by hand, or any other TURN provider. Static: whatever
//      is here is handed out until the process restarts.
//
// Neither set: no TURN, and the server behaves exactly as it did before. That
// is the right default — on one LAN a relay is pure cost.
//
// Phase 1 has no auth, so whoever can reach the signaling server can read the
// credentials it hands out. That is inherent to TURN, and the reason minting
// short-lived ones matters: a leaked credential expires on its own.

/** Where credentials are minted. Overridable so tests never touch the network. */
const CLOUDFLARE_TURN_API = "https://rtc.live.cloudflare.com/v1/turn/keys";

/** 24h. Long enough not to churn, short enough that a leak is not permanent. */
const DEFAULT_TTL_SECONDS = 86_400;

/** Refresh with a fifth of the lifetime left, so a slow retry still lands. */
const REFRESH_AT = 0.8;

export type IceSource = {
  /** What to hand a peer right now. Empty when no TURN is configured. */
  servers(): RTCIceServer[];
  /** Mint the first credential, if minting is how this is configured. */
  start(): Promise<void>;
  /** Stop refreshing. */
  stop(): void;
};

export function turnServersFromEnv(env: NodeJS.ProcessEnv): RTCIceServer[] {
  const urls = (env.TURN_URLS ?? "")
    .split(",")
    .map((url) => url.trim())
    .filter(Boolean);
  if (urls.length === 0) return [];
  const server: RTCIceServer = { urls };
  if (env.TURN_USERNAME) server.username = env.TURN_USERNAME;
  if (env.TURN_CREDENTIAL) server.credential = env.TURN_CREDENTIAL;
  return [server];
}

type Deps = {
  fetch?: typeof globalThis.fetch;
  /** Injected so a test does not wait 19 hours for a refresh. */
  setTimeout?: typeof globalThis.setTimeout;
  clearTimeout?: typeof globalThis.clearTimeout;
};

export function createIceSource(env: NodeJS.ProcessEnv, deps: Deps = {}): IceSource {
  const keyId = env.TURN_KEY_ID?.trim();
  const apiToken = env.TURN_KEY_API_TOKEN?.trim();

  // No key to mint from: whatever is in TURN_URLS, frozen for the process.
  if (!keyId || !apiToken) {
    const fixed = turnServersFromEnv(env);
    return { servers: () => fixed, start: async () => {}, stop: () => {} };
  }

  const doFetch = deps.fetch ?? globalThis.fetch;
  const schedule = deps.setTimeout ?? globalThis.setTimeout;
  const unschedule = deps.clearTimeout ?? globalThis.clearTimeout;
  const ttl = Number(env.TURN_TTL_SECONDS ?? DEFAULT_TTL_SECONDS) || DEFAULT_TTL_SECONDS;

  // Falls back to a hand-supplied pair if the very first mint fails, so a
  // provider outage at boot degrades to whatever was configured by hand rather
  // than to nothing.
  let current: RTCIceServer[] = turnServersFromEnv(env);
  let timer: ReturnType<typeof setTimeout> | undefined;
  let stopped = false;

  const mint = async (): Promise<void> => {
    if (stopped) return;
    try {
      const response = await doFetch(
        `${CLOUDFLARE_TURN_API}/${encodeURIComponent(keyId)}/credentials/generate-ice-servers`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${apiToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ ttl }),
        },
      );

      if (!response.ok) {
        // Deliberately not logging the body: on an auth failure it can echo
        // back what was sent, and this is the one secret worth not printing.
        throw new Error(`TURN credential request failed with ${response.status}`);
      }

      const body = (await response.json()) as { iceServers?: RTCIceServer | RTCIceServer[] };
      const minted = body.iceServers ? [body.iceServers].flat() : [];
      if (minted.length === 0) throw new Error("TURN credential response carried no iceServers");

      current = minted;
      console.log(`[swiff] TURN credentials minted, valid ${ttl}s`);
    } catch (cause) {
      // Never fatal. A signaling server that refuses to start because a relay
      // is unreachable takes down the LAN case too, which needs no relay.
      console.warn(
        `[swiff] could not mint TURN credentials: ${cause instanceof Error ? cause.message : cause}`,
        current.length ? "— keeping the previous ones" : "— continuing without a relay",
      );
    }

    if (stopped) return;
    timer = schedule(() => void mint(), Math.max(ttl * REFRESH_AT, 60) * 1000);
    // Refreshing is not a reason to keep the process alive.
    (timer as { unref?: () => void }).unref?.();
  };

  return {
    servers: () => current,
    start: mint,
    stop: () => {
      stopped = true;
      if (timer) unschedule(timer);
    },
  };
}
